# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: edu/uci/ics/amber/engine/architecture/python/proxy_message.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto

from ... import common as __common__
from .. import rpc as _rpc__


@dataclass(eq=False, repr=False)
class ControlPayloadV2(betterproto.Message):
    control_invocation: "_rpc__.ControlInvocation" = betterproto.message_field(
        1, group="value"
    )
    return_invocation: "_rpc__.ReturnInvocation" = betterproto.message_field(
        2, group="value"
    )


@dataclass(eq=False, repr=False)
class PythonDataHeader(betterproto.Message):
    tag: "__common__.ActorVirtualIdentity" = betterproto.message_field(1)
    payload_type: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class PythonControlMessage(betterproto.Message):
    tag: "__common__.ActorVirtualIdentity" = betterproto.message_field(1)
    payload: "ControlPayloadV2" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class PythonActorMessage(betterproto.Message):
    payload: "__common__.ActorCommand" = betterproto.message_field(1)
