// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.architecture.controller.controllerrpc

object ControllerrpcProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    edu.uci.ics.amber.engine.architecture.sendsemantics.partitionings.PartitioningsProto,
    edu.uci.ics.amber.engine.common.virtualidentity.VirtualidentityProto,
    com.google.protobuf.timestamp.TimestampProto,
    com.google.protobuf.empty.EmptyProto,
    com.google.protobuf.any.AnyProto,
    scalapb.options.ScalapbProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      edu.uci.ics.amber.engine.architecture.controller.controllerrpc.WorkerSet,
      edu.uci.ics.amber.engine.architecture.controller.controllerrpc.RpcPayload,
      edu.uci.ics.amber.engine.architecture.controller.controllerrpc.WorkerRpcCallsRequest,
      edu.uci.ics.amber.engine.architecture.controller.controllerrpc.WorkerRpcCallsResponse,
      edu.uci.ics.amber.engine.architecture.controller.controllerrpc.LocalBreakpointTriggeredEvent,
      edu.uci.ics.amber.engine.architecture.controller.controllerrpc.LocalOperatorExceptionEvent,
      edu.uci.ics.amber.engine.architecture.controller.controllerrpc.ModifyLogicRequest,
      edu.uci.ics.amber.engine.architecture.controller.controllerrpc.ModifyLogicResponse,
      edu.uci.ics.amber.engine.architecture.controller.controllerrpc.PythonConsoleMessageEvent,
      edu.uci.ics.amber.engine.architecture.controller.controllerrpc.QueryWorkerStatsRequest,
      edu.uci.ics.amber.engine.architecture.controller.controllerrpc.QueryWorkerStatsResponse,
      edu.uci.ics.amber.engine.architecture.controller.controllerrpc.RegionsTimeSlotExpiredEvent,
      edu.uci.ics.amber.engine.architecture.controller.controllerrpc.SkewDetectionRequest,
      edu.uci.ics.amber.engine.architecture.controller.controllerrpc.SkewDetectionResponse,
      edu.uci.ics.amber.engine.architecture.controller.controllerrpc.WorkerExecutionStartedEvent,
      edu.uci.ics.amber.engine.architecture.controller.controllerrpc.FatalErrorEvent,
      edu.uci.ics.amber.engine.architecture.controller.controllerrpc.LinkWorkersRequest,
      edu.uci.ics.amber.engine.architecture.controller.controllerrpc.LinkWorkersResponse,
      edu.uci.ics.amber.engine.architecture.controller.controllerrpc.AssignBreakpointRequest,
      edu.uci.ics.amber.engine.architecture.controller.controllerrpc.AssignBreakpointResponse,
      edu.uci.ics.amber.engine.architecture.controller.controllerrpc.EpochMarkerRequest,
      edu.uci.ics.amber.engine.architecture.controller.controllerrpc.EpochMarkerResponse,
      edu.uci.ics.amber.engine.architecture.controller.controllerrpc.WorkerExecutionCompletedEvent,
      edu.uci.ics.amber.engine.architecture.controller.controllerrpc.LinkCompletedEvent
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CkRlZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvYXJjaGl0ZWN0dXJlL2NvbnRyb2xsZXIvY29udHJvbGxlcnJwYy5wcm90bxIwZ
  WR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS5jb250cm9sbGVyGkdlZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvY
  XJjaGl0ZWN0dXJlL3NlbmRzZW1hbnRpY3MvcGFydGl0aW9uaW5ncy5wcm90bxo1ZWR1L3VjaS9pY3MvYW1iZXIvZW5naW5lL2Nvb
  W1vbi92aXJ0dWFsaWRlbnRpdHkucHJvdG8aH2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAucHJvdG8aG2dvb2dsZS9wcm90b2J1Z
  i9lbXB0eS5wcm90bxoZZ29vZ2xlL3Byb3RvYnVmL2FueS5wcm90bxoVc2NhbGFwYi9zY2FsYXBiLnByb3RvImcKCVdvcmtlclNld
  BJaCgZ3b3JrZXIYASADKAsyNS5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuY29tbW9uLkFjdG9yVmlydHVhbElkZW50aXR5QgviP
  wgSBndvcmtlclIGd29ya2VyIq0BCgpScGNQYXlsb2FkEmEKCXdvcmtlcl9pZBgBIAEoCzI1LmVkdS51Y2kuaWNzLmFtYmVyLmVuZ
  2luZS5jb21tb24uQWN0b3JWaXJ0dWFsSWRlbnRpdHlCDeI/ChIId29ya2VySWRSCHdvcmtlcklkEjwKB3BheWxvYWQYAiABKAsyF
  C5nb29nbGUucHJvdG9idWYuQW55QgziPwkSB3BheWxvYWRSB3BheWxvYWQikwEKFVdvcmtlclJwY0NhbGxzUmVxdWVzdBJ6Cg9jY
  WxsX2NvbGxlY3Rpb24YASADKAsyPC5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLmNvbnRyb2xsZXIuUnBjU
  GF5bG9hZEIT4j8QEg5jYWxsQ29sbGVjdGlvblIOY2FsbENvbGxlY3Rpb24ikQEKFldvcmtlclJwY0NhbGxzUmVzcG9uc2USdwoOc
  mV0X2NvbGxlY3Rpb24YASADKAsyPC5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLmNvbnRyb2xsZXIuUnBjU
  GF5bG9hZEIS4j8PEg1yZXRDb2xsZWN0aW9uUg1yZXRDb2xsZWN0aW9uIh8KHUxvY2FsQnJlYWtwb2ludFRyaWdnZXJlZEV2ZW50I
  kUKG0xvY2FsT3BlcmF0b3JFeGNlcHRpb25FdmVudBImCgdtZXNzYWdlGAEgASgJQgziPwkSB21lc3NhZ2VSB21lc3NhZ2UiFAoST
  W9kaWZ5TG9naWNSZXF1ZXN0IhUKE01vZGlmeUxvZ2ljUmVzcG9uc2Ui3gEKGVB5dGhvbkNvbnNvbGVNZXNzYWdlRXZlbnQSSwoJd
  GltZXN0YW1wGAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEIR4j8OEgl0aW1lc3RhbXDwAQFSCXRpbWVzdGFtcBInC
  ghtc2dfdHlwZRgCIAEoCUIM4j8JEgdtc2dUeXBlUgdtc2dUeXBlEiMKBnNvdXJjZRgDIAEoCUIL4j8IEgZzb3VyY2VSBnNvdXJjZ
  RImCgdtZXNzYWdlGAQgASgJQgziPwkSB21lc3NhZ2VSB21lc3NhZ2UiGQoXUXVlcnlXb3JrZXJTdGF0c1JlcXVlc3QiGgoYUXVlc
  nlXb3JrZXJTdGF0c1Jlc3BvbnNlIh0KG1JlZ2lvbnNUaW1lU2xvdEV4cGlyZWRFdmVudCIWChRTa2V3RGV0ZWN0aW9uUmVxdWVzd
  CIXChVTa2V3RGV0ZWN0aW9uUmVzcG9uc2UiHQobV29ya2VyRXhlY3V0aW9uU3RhcnRlZEV2ZW50IhEKD0ZhdGFsRXJyb3JFdmVud
  CIUChJMaW5rV29ya2Vyc1JlcXVlc3QiFQoTTGlua1dvcmtlcnNSZXNwb25zZSIZChdBc3NpZ25CcmVha3BvaW50UmVxdWVzdCIaC
  hhBc3NpZ25CcmVha3BvaW50UmVzcG9uc2UiFAoSRXBvY2hNYXJrZXJSZXF1ZXN0IhUKE0Vwb2NoTWFya2VyUmVzcG9uc2UiHwodV
  29ya2VyRXhlY3V0aW9uQ29tcGxldGVkRXZlbnQibAoSTGlua0NvbXBsZXRlZEV2ZW50ElYKB2xpbmtfaWQYASABKAsyLS5lZHUud
  WNpLmljcy5hbWJlci5lbmdpbmUuY29tbW9uLkxpbmtJZGVudGl0eUIO4j8LEgZsaW5rSWTwAQFSBmxpbmtJZDLrEAoNQ29udHJvb
  GxlclJwYxKpAQoQQXNzaWduQnJlYWtwb2ludBJJLmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUuY29udHJvb
  Gxlci5Bc3NpZ25CcmVha3BvaW50UmVxdWVzdBpKLmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUuY29udHJvb
  Gxlci5Bc3NpZ25CcmVha3BvaW50UmVzcG9uc2USmgEKC0Vwb2NoTWFya2VyEkQuZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY
  2hpdGVjdHVyZS5jb250cm9sbGVyLkVwb2NoTWFya2VyUmVxdWVzdBpFLmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY
  3R1cmUuY29udHJvbGxlci5FcG9jaE1hcmtlclJlc3BvbnNlEmcKCkZhdGFsRXJyb3ISQS5lZHUudWNpLmljcy5hbWJlci5lbmdpb
  mUuYXJjaGl0ZWN0dXJlLmNvbnRyb2xsZXIuRmF0YWxFcnJvckV2ZW50GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5EpoBCgtMaW5rV
  29ya2VycxJELmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUuY29udHJvbGxlci5MaW5rV29ya2Vyc1JlcXVlc
  3QaRS5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLmNvbnRyb2xsZXIuTGlua1dvcmtlcnNSZXNwb25zZRJtC
  g1MaW5rQ29tcGxldGVkEkQuZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS5jb250cm9sbGVyLkxpbmtDb21wb
  GV0ZWRFdmVudBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRKDAQoYTG9jYWxCcmVha3BvaW50VHJpZ2dlcmVkEk8uZWR1LnVjaS5pY
  3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS5jb250cm9sbGVyLkxvY2FsQnJlYWtwb2ludFRyaWdnZXJlZEV2ZW50GhYuZ29vZ
  2xlLnByb3RvYnVmLkVtcHR5En8KFkxvY2FsT3BlcmF0b3JFeGNlcHRpb24STS5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJja
  Gl0ZWN0dXJlLmNvbnRyb2xsZXIuTG9jYWxPcGVyYXRvckV4Y2VwdGlvbkV2ZW50GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5EpoBC
  gtNb2RpZnlMb2dpYxJELmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUuY29udHJvbGxlci5Nb2RpZnlMb2dpY
  1JlcXVlc3QaRS5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLmNvbnRyb2xsZXIuTW9kaWZ5TG9naWNSZXNwb
  25zZRJ7ChRQeXRob25Db25zb2xlTWVzc2FnZRJLLmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUuY29udHJvb
  Gxlci5QeXRob25Db25zb2xlTWVzc2FnZUV2ZW50GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5EqkBChBRdWVyeVdvcmtlclN0YXRzE
  kkuZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS5jb250cm9sbGVyLlF1ZXJ5V29ya2VyU3RhdHNSZXF1ZXN0G
  kouZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS5jb250cm9sbGVyLlF1ZXJ5V29ya2VyU3RhdHNSZXNwb25zZ
  RJ/ChZSZWdpb25zVGltZVNsb3RFeHBpcmVkEk0uZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS5jb250cm9sb
  GVyLlJlZ2lvbnNUaW1lU2xvdEV4cGlyZWRFdmVudBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRKgAQoNU2tld0RldGVjdGlvbhJGL
  mVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUuY29udHJvbGxlci5Ta2V3RGV0ZWN0aW9uUmVxdWVzdBpHLmVkd
  S51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUuY29udHJvbGxlci5Ta2V3RGV0ZWN0aW9uUmVzcG9uc2USfwoWV29ya
  2VyRXhlY3V0aW9uU3RhcnRlZBJNLmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUuY29udHJvbGxlci5Xb3JrZ
  XJFeGVjdXRpb25TdGFydGVkRXZlbnQaFi5nb29nbGUucHJvdG9idWYuRW1wdHkSgwEKGFdvcmtlckV4ZWN1dGlvbkNvbXBsZXRlZ
  BJPLmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUuY29udHJvbGxlci5Xb3JrZXJFeGVjdXRpb25Db21wbGV0Z
  WRFdmVudBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRKjAQoOV29ya2VyUnBjQ2FsbHMSRy5lZHUudWNpLmljcy5hbWJlci5lbmdpb
  mUuYXJjaGl0ZWN0dXJlLmNvbnRyb2xsZXIuV29ya2VyUnBjQ2FsbHNSZXF1ZXN0GkguZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lL
  mFyY2hpdGVjdHVyZS5jb250cm9sbGVyLldvcmtlclJwY0NhbGxzUmVzcG9uc2VCB+I/BEgAWABiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      edu.uci.ics.amber.engine.architecture.sendsemantics.partitionings.PartitioningsProto.javaDescriptor,
      edu.uci.ics.amber.engine.common.virtualidentity.VirtualidentityProto.javaDescriptor,
      com.google.protobuf.timestamp.TimestampProto.javaDescriptor,
      com.google.protobuf.empty.EmptyProto.javaDescriptor,
      com.google.protobuf.any.AnyProto.javaDescriptor,
      scalapb.options.ScalapbProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}