// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.common.workflow

object WorkflowProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    edu.uci.ics.amber.engine.common.virtualidentity.VirtualidentityProto,
    scalapb.options.ScalapbProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      edu.uci.ics.amber.engine.common.workflow.PortIdentity,
      edu.uci.ics.amber.engine.common.workflow.InputPort,
      edu.uci.ics.amber.engine.common.workflow.OutputPort,
      edu.uci.ics.amber.engine.common.workflow.PhysicalLink
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Ci5lZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvY29tbW9uL3dvcmtmbG93LnByb3RvEh9lZHUudWNpLmljcy5hbWJlci5lbmdpb
  mUuY29tbW9uGjVlZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvY29tbW9uL3ZpcnR1YWxpZGVudGl0eS5wcm90bxoVc2NhbGFwYi9zY
  2FsYXBiLnByb3RvIlIKDFBvcnRJZGVudGl0eRIXCgJpZBgBIAEoBUIH4j8EEgJpZFICaWQSKQoIaW50ZXJuYWwYAiABKAhCDeI/C
  hIIaW50ZXJuYWxSCGludGVybmFsIrACCglJbnB1dFBvcnQSSQoCaWQYASABKAsyLS5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuY
  29tbW9uLlBvcnRJZGVudGl0eUIK4j8HEgJpZPABAVICaWQSMgoLZGlzcGxheU5hbWUYAiABKAlCEOI/DRILZGlzcGxheU5hbWVSC
  2Rpc3BsYXlOYW1lEj4KD2FsbG93TXVsdGlMaW5rcxgDIAEoCEIU4j8REg9hbGxvd011bHRpTGlua3NSD2FsbG93TXVsdGlMaW5rc
  xJkCgxkZXBlbmRlbmNpZXMYBCADKAsyLS5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuY29tbW9uLlBvcnRJZGVudGl0eUIR4j8OE
  gxkZXBlbmRlbmNpZXNSDGRlcGVuZGVuY2llcyL2AQoKT3V0cHV0UG9ydBJJCgJpZBgBIAEoCzItLmVkdS51Y2kuaWNzLmFtYmVyL
  mVuZ2luZS5jb21tb24uUG9ydElkZW50aXR5QgriPwcSAmlk8AEBUgJpZBIyCgtkaXNwbGF5TmFtZRgCIAEoCUIQ4j8NEgtkaXNwb
  GF5TmFtZVILZGlzcGxheU5hbWUSKQoIYmxvY2tpbmcYAyABKAhCDeI/ChIIYmxvY2tpbmdSCGJsb2NraW5nEj4KD3N0b3JhZ2VMb
  2NhdGlvbhgEIAEoCUIU4j8REg9zdG9yYWdlTG9jYXRpb25SD3N0b3JhZ2VMb2NhdGlvbiKOAwoMUGh5c2ljYWxMaW5rEmEKCGZyb
  21PcElkGAEgASgLMjMuZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmNvbW1vbi5QaHlzaWNhbE9wSWRlbnRpdHlCEOI/DRIIZnJvb
  U9wSWTwAQFSCGZyb21PcElkEmEKCmZyb21Qb3J0SWQYAiABKAsyLS5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuY29tbW9uLlBvc
  nRJZGVudGl0eUIS4j8PEgpmcm9tUG9ydElk8AEBUgpmcm9tUG9ydElkElsKBnRvT3BJZBgDIAEoCzIzLmVkdS51Y2kuaWNzLmFtY
  mVyLmVuZ2luZS5jb21tb24uUGh5c2ljYWxPcElkZW50aXR5Qg7iPwsSBnRvT3BJZPABAVIGdG9PcElkElsKCHRvUG9ydElkGAQgA
  SgLMi0uZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmNvbW1vbi5Qb3J0SWRlbnRpdHlCEOI/DRIIdG9Qb3J0SWTwAQFSCHRvUG9yd
  ElkQgniPwZIAFgAeABiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      edu.uci.ics.amber.engine.common.virtualidentity.VirtualidentityProto.javaDescriptor,
      scalapb.options.ScalapbProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}