// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.common.ambermessage

@SerialVersionUID(0L)
final case class PythonDataHeader(
    tag: edu.uci.ics.amber.engine.common.virtualidentity.ActorVirtualIdentity,
    isEnd: _root_.scala.Boolean,
    isEpoch: _root_.scala.Boolean,
    epochDest: edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[PythonDataHeader] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = tag
        if (__value != edu.uci.ics.amber.engine.common.virtualidentity.ActorVirtualIdentity.defaultInstance) {
          __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
        }
      };
      
      {
        val __value = isEnd
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(2, __value)
        }
      };
      
      {
        val __value = isEpoch
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(3, __value)
        }
      };
      
      {
        val __value = epochDest
        if (__value != edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity.defaultInstance) {
          __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
        }
      };
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = tag
        if (__v != edu.uci.ics.amber.engine.common.virtualidentity.ActorVirtualIdentity.defaultInstance) {
          _output__.writeTag(1, 2)
          _output__.writeUInt32NoTag(__v.serializedSize)
          __v.writeTo(_output__)
        }
      };
      {
        val __v = isEnd
        if (__v != false) {
          _output__.writeBool(2, __v)
        }
      };
      {
        val __v = isEpoch
        if (__v != false) {
          _output__.writeBool(3, __v)
        }
      };
      {
        val __v = epochDest
        if (__v != edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity.defaultInstance) {
          _output__.writeTag(4, 2)
          _output__.writeUInt32NoTag(__v.serializedSize)
          __v.writeTo(_output__)
        }
      };
    }
    def withTag(__v: edu.uci.ics.amber.engine.common.virtualidentity.ActorVirtualIdentity): PythonDataHeader = copy(tag = __v)
    def withIsEnd(__v: _root_.scala.Boolean): PythonDataHeader = copy(isEnd = __v)
    def withIsEpoch(__v: _root_.scala.Boolean): PythonDataHeader = copy(isEpoch = __v)
    def withEpochDest(__v: edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity): PythonDataHeader = copy(epochDest = __v)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = tag
          if (__t != edu.uci.ics.amber.engine.common.virtualidentity.ActorVirtualIdentity.defaultInstance) __t else null
        }
        case 2 => {
          val __t = isEnd
          if (__t != false) __t else null
        }
        case 3 => {
          val __t = isEpoch
          if (__t != false) __t else null
        }
        case 4 => {
          val __t = epochDest
          if (__t != edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity.defaultInstance) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => tag.toPMessage
        case 2 => _root_.scalapb.descriptors.PBoolean(isEnd)
        case 3 => _root_.scalapb.descriptors.PBoolean(isEpoch)
        case 4 => epochDest.toPMessage
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToSingleLineUnicodeString(this)
    def companion = edu.uci.ics.amber.engine.common.ambermessage.PythonDataHeader
    // @@protoc_insertion_point(GeneratedMessage[edu.uci.ics.amber.engine.common.PythonDataHeader])
}

object PythonDataHeader extends scalapb.GeneratedMessageCompanion[edu.uci.ics.amber.engine.common.ambermessage.PythonDataHeader] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[edu.uci.ics.amber.engine.common.ambermessage.PythonDataHeader] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): edu.uci.ics.amber.engine.common.ambermessage.PythonDataHeader = {
    var __tag: _root_.scala.Option[edu.uci.ics.amber.engine.common.virtualidentity.ActorVirtualIdentity] = _root_.scala.None
    var __isEnd: _root_.scala.Boolean = false
    var __isEpoch: _root_.scala.Boolean = false
    var __epochDest: _root_.scala.Option[edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity] = _root_.scala.None
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __tag = _root_.scala.Some(__tag.fold(_root_.scalapb.LiteParser.readMessage[edu.uci.ics.amber.engine.common.virtualidentity.ActorVirtualIdentity](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 16 =>
          __isEnd = _input__.readBool()
        case 24 =>
          __isEpoch = _input__.readBool()
        case 34 =>
          __epochDest = _root_.scala.Some(__epochDest.fold(_root_.scalapb.LiteParser.readMessage[edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case tag => _input__.skipField(tag)
      }
    }
    edu.uci.ics.amber.engine.common.ambermessage.PythonDataHeader(
        tag = __tag.getOrElse(edu.uci.ics.amber.engine.common.virtualidentity.ActorVirtualIdentity.defaultInstance),
        isEnd = __isEnd,
        isEpoch = __isEpoch,
        epochDest = __epochDest.getOrElse(edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity.defaultInstance)
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[edu.uci.ics.amber.engine.common.ambermessage.PythonDataHeader] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      edu.uci.ics.amber.engine.common.ambermessage.PythonDataHeader(
        tag = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[edu.uci.ics.amber.engine.common.virtualidentity.ActorVirtualIdentity]).getOrElse(edu.uci.ics.amber.engine.common.virtualidentity.ActorVirtualIdentity.defaultInstance),
        isEnd = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Boolean]).getOrElse(false),
        isEpoch = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Boolean]).getOrElse(false),
        epochDest = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity]).getOrElse(edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity.defaultInstance)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = AmbermessageProto.javaDescriptor.getMessageTypes().get(3)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = AmbermessageProto.scalaDescriptor.messages(3)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = edu.uci.ics.amber.engine.common.virtualidentity.ActorVirtualIdentity
      case 4 => __out = edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = edu.uci.ics.amber.engine.common.ambermessage.PythonDataHeader(
    tag = edu.uci.ics.amber.engine.common.virtualidentity.ActorVirtualIdentity.defaultInstance,
    isEnd = false,
    isEpoch = false,
    epochDest = edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity.defaultInstance
  )
  implicit class PythonDataHeaderLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, edu.uci.ics.amber.engine.common.ambermessage.PythonDataHeader]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, edu.uci.ics.amber.engine.common.ambermessage.PythonDataHeader](_l) {
    def tag: _root_.scalapb.lenses.Lens[UpperPB, edu.uci.ics.amber.engine.common.virtualidentity.ActorVirtualIdentity] = field(_.tag)((c_, f_) => c_.copy(tag = f_))
    def isEnd: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.isEnd)((c_, f_) => c_.copy(isEnd = f_))
    def isEpoch: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.isEpoch)((c_, f_) => c_.copy(isEpoch = f_))
    def epochDest: _root_.scalapb.lenses.Lens[UpperPB, edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity] = field(_.epochDest)((c_, f_) => c_.copy(epochDest = f_))
  }
  final val TAG_FIELD_NUMBER = 1
  final val IS_END_FIELD_NUMBER = 2
  final val IS_EPOCH_FIELD_NUMBER = 3
  final val EPOCH_DEST_FIELD_NUMBER = 4
  def of(
    tag: edu.uci.ics.amber.engine.common.virtualidentity.ActorVirtualIdentity,
    isEnd: _root_.scala.Boolean,
    isEpoch: _root_.scala.Boolean,
    epochDest: edu.uci.ics.amber.engine.common.virtualidentity.LayerIdentity
  ): _root_.edu.uci.ics.amber.engine.common.ambermessage.PythonDataHeader = _root_.edu.uci.ics.amber.engine.common.ambermessage.PythonDataHeader(
    tag,
    isEnd,
    isEpoch,
    epochDest
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[edu.uci.ics.amber.engine.common.PythonDataHeader])
}
