// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.architecture.worker.workerrpc

@SerialVersionUID(0L)
final case class SchedulerTimeSlotEventRequest(
    timeSlotExpired: _root_.scala.Boolean = false
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[SchedulerTimeSlotEventRequest] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = timeSlotExpired
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(1, __value)
        }
      };
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = timeSlotExpired
        if (__v != false) {
          _output__.writeBool(1, __v)
        }
      };
    }
    def withTimeSlotExpired(__v: _root_.scala.Boolean): SchedulerTimeSlotEventRequest = copy(timeSlotExpired = __v)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = timeSlotExpired
          if (__t != false) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PBoolean(timeSlotExpired)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToSingleLineUnicodeString(this)
    def companion = edu.uci.ics.amber.engine.architecture.worker.workerrpc.SchedulerTimeSlotEventRequest
    // @@protoc_insertion_point(GeneratedMessage[edu.uci.ics.amber.engine.architecture.worker.SchedulerTimeSlotEventRequest])
}

object SchedulerTimeSlotEventRequest extends scalapb.GeneratedMessageCompanion[edu.uci.ics.amber.engine.architecture.worker.workerrpc.SchedulerTimeSlotEventRequest] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[edu.uci.ics.amber.engine.architecture.worker.workerrpc.SchedulerTimeSlotEventRequest] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): edu.uci.ics.amber.engine.architecture.worker.workerrpc.SchedulerTimeSlotEventRequest = {
    var __timeSlotExpired: _root_.scala.Boolean = false
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 8 =>
          __timeSlotExpired = _input__.readBool()
        case tag => _input__.skipField(tag)
      }
    }
    edu.uci.ics.amber.engine.architecture.worker.workerrpc.SchedulerTimeSlotEventRequest(
        timeSlotExpired = __timeSlotExpired
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[edu.uci.ics.amber.engine.architecture.worker.workerrpc.SchedulerTimeSlotEventRequest] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      edu.uci.ics.amber.engine.architecture.worker.workerrpc.SchedulerTimeSlotEventRequest(
        timeSlotExpired = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Boolean]).getOrElse(false)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = WorkerrpcProto.javaDescriptor.getMessageTypes().get(37)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = WorkerrpcProto.scalaDescriptor.messages(37)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = edu.uci.ics.amber.engine.architecture.worker.workerrpc.SchedulerTimeSlotEventRequest(
    timeSlotExpired = false
  )
  implicit class SchedulerTimeSlotEventRequestLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, edu.uci.ics.amber.engine.architecture.worker.workerrpc.SchedulerTimeSlotEventRequest]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, edu.uci.ics.amber.engine.architecture.worker.workerrpc.SchedulerTimeSlotEventRequest](_l) {
    def timeSlotExpired: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.timeSlotExpired)((c_, f_) => c_.copy(timeSlotExpired = f_))
  }
  final val TIME_SLOT_EXPIRED_FIELD_NUMBER = 1
  def of(
    timeSlotExpired: _root_.scala.Boolean
  ): _root_.edu.uci.ics.amber.engine.architecture.worker.workerrpc.SchedulerTimeSlotEventRequest = _root_.edu.uci.ics.amber.engine.architecture.worker.workerrpc.SchedulerTimeSlotEventRequest(
    timeSlotExpired
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[edu.uci.ics.amber.engine.architecture.worker.SchedulerTimeSlotEventRequest])
}
