// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.architecture.controller.controllercallservice

@SerialVersionUID(0L)
final case class PythonConsoleMessageEvent(
    timestamp: com.google.protobuf.timestamp.Timestamp = com.google.protobuf.timestamp.Timestamp.defaultInstance,
    msgType: _root_.scala.Predef.String = "",
    source: _root_.scala.Predef.String = "",
    message: _root_.scala.Predef.String = ""
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[PythonConsoleMessageEvent] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = timestamp
        if (__value != com.google.protobuf.timestamp.Timestamp.defaultInstance) {
          __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
        }
      };
      
      {
        val __value = msgType
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = source
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      
      {
        val __value = message
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
        }
      };
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = timestamp
        if (__v != com.google.protobuf.timestamp.Timestamp.defaultInstance) {
          _output__.writeTag(1, 2)
          _output__.writeUInt32NoTag(__v.serializedSize)
          __v.writeTo(_output__)
        }
      };
      {
        val __v = msgType
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = source
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      {
        val __v = message
        if (!__v.isEmpty) {
          _output__.writeString(4, __v)
        }
      };
    }
    def withTimestamp(__v: com.google.protobuf.timestamp.Timestamp): PythonConsoleMessageEvent = copy(timestamp = __v)
    def withMsgType(__v: _root_.scala.Predef.String): PythonConsoleMessageEvent = copy(msgType = __v)
    def withSource(__v: _root_.scala.Predef.String): PythonConsoleMessageEvent = copy(source = __v)
    def withMessage(__v: _root_.scala.Predef.String): PythonConsoleMessageEvent = copy(message = __v)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = timestamp
          if (__t != com.google.protobuf.timestamp.Timestamp.defaultInstance) __t else null
        }
        case 2 => {
          val __t = msgType
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = source
          if (__t != "") __t else null
        }
        case 4 => {
          val __t = message
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => timestamp.toPMessage
        case 2 => _root_.scalapb.descriptors.PString(msgType)
        case 3 => _root_.scalapb.descriptors.PString(source)
        case 4 => _root_.scalapb.descriptors.PString(message)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToSingleLineUnicodeString(this)
    def companion = edu.uci.ics.amber.engine.architecture.controller.controllercallservice.PythonConsoleMessageEvent
    // @@protoc_insertion_point(GeneratedMessage[edu.uci.ics.amber.engine.architecture.controller.PythonConsoleMessageEvent])
}

object PythonConsoleMessageEvent extends scalapb.GeneratedMessageCompanion[edu.uci.ics.amber.engine.architecture.controller.controllercallservice.PythonConsoleMessageEvent] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[edu.uci.ics.amber.engine.architecture.controller.controllercallservice.PythonConsoleMessageEvent] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): edu.uci.ics.amber.engine.architecture.controller.controllercallservice.PythonConsoleMessageEvent = {
    var __timestamp: _root_.scala.Option[com.google.protobuf.timestamp.Timestamp] = _root_.scala.None
    var __msgType: _root_.scala.Predef.String = ""
    var __source: _root_.scala.Predef.String = ""
    var __message: _root_.scala.Predef.String = ""
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __timestamp = _root_.scala.Some(__timestamp.fold(_root_.scalapb.LiteParser.readMessage[com.google.protobuf.timestamp.Timestamp](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 18 =>
          __msgType = _input__.readStringRequireUtf8()
        case 26 =>
          __source = _input__.readStringRequireUtf8()
        case 34 =>
          __message = _input__.readStringRequireUtf8()
        case tag => _input__.skipField(tag)
      }
    }
    edu.uci.ics.amber.engine.architecture.controller.controllercallservice.PythonConsoleMessageEvent(
        timestamp = __timestamp.getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance),
        msgType = __msgType,
        source = __source,
        message = __message
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[edu.uci.ics.amber.engine.architecture.controller.controllercallservice.PythonConsoleMessageEvent] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      edu.uci.ics.amber.engine.architecture.controller.controllercallservice.PythonConsoleMessageEvent(
        timestamp = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[com.google.protobuf.timestamp.Timestamp]).getOrElse(com.google.protobuf.timestamp.Timestamp.defaultInstance),
        msgType = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        source = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        message = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = ControllercallserviceProto.javaDescriptor.getMessageTypes().get(8)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = ControllercallserviceProto.scalaDescriptor.messages(8)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = com.google.protobuf.timestamp.Timestamp
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = edu.uci.ics.amber.engine.architecture.controller.controllercallservice.PythonConsoleMessageEvent(
    timestamp = com.google.protobuf.timestamp.Timestamp.defaultInstance,
    msgType = "",
    source = "",
    message = ""
  )
  implicit class PythonConsoleMessageEventLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, edu.uci.ics.amber.engine.architecture.controller.controllercallservice.PythonConsoleMessageEvent]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, edu.uci.ics.amber.engine.architecture.controller.controllercallservice.PythonConsoleMessageEvent](_l) {
    def timestamp: _root_.scalapb.lenses.Lens[UpperPB, com.google.protobuf.timestamp.Timestamp] = field(_.timestamp)((c_, f_) => c_.copy(timestamp = f_))
    def msgType: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.msgType)((c_, f_) => c_.copy(msgType = f_))
    def source: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.source)((c_, f_) => c_.copy(source = f_))
    def message: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.message)((c_, f_) => c_.copy(message = f_))
  }
  final val TIMESTAMP_FIELD_NUMBER = 1
  final val MSG_TYPE_FIELD_NUMBER = 2
  final val SOURCE_FIELD_NUMBER = 3
  final val MESSAGE_FIELD_NUMBER = 4
  def of(
    timestamp: com.google.protobuf.timestamp.Timestamp,
    msgType: _root_.scala.Predef.String,
    source: _root_.scala.Predef.String,
    message: _root_.scala.Predef.String
  ): _root_.edu.uci.ics.amber.engine.architecture.controller.controllercallservice.PythonConsoleMessageEvent = _root_.edu.uci.ics.amber.engine.architecture.controller.controllercallservice.PythonConsoleMessageEvent(
    timestamp,
    msgType,
    source,
    message
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[edu.uci.ics.amber.engine.architecture.controller.PythonConsoleMessageEvent])
}
