// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.common.actormessage

object ActormessageProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    scalapb.options.ScalapbProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      edu.uci.ics.amber.engine.common.actormessage.HelloRequest,
      edu.uci.ics.amber.engine.common.actormessage.HelloReply,
      edu.uci.ics.amber.engine.common.actormessage.Backpressure,
      edu.uci.ics.amber.engine.common.actormessage.CreditUpdate,
      edu.uci.ics.amber.engine.common.actormessage.ActorCommandMessage,
      edu.uci.ics.amber.engine.common.actormessage.PythonActorMessage
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CjJlZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvY29tbW9uL2FjdG9ybWVzc2FnZS5wcm90bxIfZWR1LnVjaS5pY3MuYW1iZXIuZ
  W5naW5lLmNvbW1vbhoVc2NhbGFwYi9zY2FsYXBiLnByb3RvIi0KDEhlbGxvUmVxdWVzdBIdCgRuYW1lGAEgASgJQgniPwYSBG5hb
  WVSBG5hbWUiNAoKSGVsbG9SZXBseRImCgdtZXNzYWdlGAEgASgJQgziPwkSB21lc3NhZ2VSB21lc3NhZ2UiWAoMQmFja3ByZXNzd
  XJlEkgKE2VuYWJsZV9iYWNrcHJlc3N1cmUYASABKAhCF+I/FBISZW5hYmxlQmFja3ByZXNzdXJlUhJlbmFibGVCYWNrcHJlc3N1c
  mUiDgoMQ3JlZGl0VXBkYXRlIu8BCgxBY3RvckNvbW1hbmQSZgoMYmFja3ByZXNzdXJlGAEgASgLMi0uZWR1LnVjaS5pY3MuYW1iZ
  XIuZW5naW5lLmNvbW1vbi5CYWNrcHJlc3N1cmVCEeI/DhIMYmFja3ByZXNzdXJlSABSDGJhY2twcmVzc3VyZRJnCg1jcmVkaXRfd
  XBkYXRlGAIgASgLMi0uZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmNvbW1vbi5DcmVkaXRVcGRhdGVCEeI/DhIMY3JlZGl0VXBkY
  XRlSABSDGNyZWRpdFVwZGF0ZUIOCgxzZWFsZWRfdmFsdWUibgoSUHl0aG9uQWN0b3JNZXNzYWdlElgKB3BheWxvYWQYASABKAsyL
  S5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuY29tbW9uLkFjdG9yQ29tbWFuZEIP4j8MEgdwYXlsb2Fk8AEBUgdwYXlsb2FkMnMKB
  0dyZWV0ZXISaAoIU2F5SGVsbG8SLS5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuY29tbW9uLkhlbGxvUmVxdWVzdBorLmVkdS51Y
  2kuaWNzLmFtYmVyLmVuZ2luZS5jb21tb24uSGVsbG9SZXBseSIAQgniPwZIAFgAeAFiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      scalapb.options.ScalapbProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}