// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.architecture.python

object ProxyMessageProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    edu.uci.ics.amber.engine.architecture.rpc.ControlCommandsProto,
    edu.uci.ics.amber.engine.architecture.rpc.ControlReturnsProto,
    edu.uci.ics.amber.engine.common.VirtualIdentityProto,
    edu.uci.ics.amber.engine.common.ActorMessageProto,
    scalapb.options.ScalapbProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      edu.uci.ics.amber.engine.architecture.python.ControlPayloadV2,
      edu.uci.ics.amber.engine.architecture.python.PythonDataHeader,
      edu.uci.ics.amber.engine.architecture.python.PythonControlMessage,
      edu.uci.ics.amber.engine.architecture.python.PythonActorMessage
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CkBlZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvYXJjaGl0ZWN0dXJlL3B5dGhvbi9wcm94eV9tZXNzYWdlLnByb3RvEixlZHUud
  WNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLnB5dGhvbhpAZWR1L3VjaS9pY3MvYW1iZXIvZW5naW5lL2FyY2hpdGVjd
  HVyZS9ycGMvY29udHJvbF9jb21tYW5kcy5wcm90bxo/ZWR1L3VjaS9pY3MvYW1iZXIvZW5naW5lL2FyY2hpdGVjdHVyZS9ycGMvY
  29udHJvbF9yZXR1cm5zLnByb3RvGjZlZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvY29tbW9uL3ZpcnR1YWxfaWRlbnRpdHkucHJvd
  G8aM2VkdS91Y2kvaWNzL2FtYmVyL2VuZ2luZS9jb21tb24vYWN0b3JfbWVzc2FnZS5wcm90bxoVc2NhbGFwYi9zY2FsYXBiLnByb
  3RvIqcCChBDb250cm9sUGF5bG9hZFYyEoUBChJjb250cm9sX2ludm9jYXRpb24YASABKAsyPC5lZHUudWNpLmljcy5hbWJlci5lb
  mdpbmUuYXJjaGl0ZWN0dXJlLnJwYy5Db250cm9sSW52b2NhdGlvbkIW4j8TEhFjb250cm9sSW52b2NhdGlvbkgAUhFjb250cm9sS
  W52b2NhdGlvbhKBAQoRcmV0dXJuX2ludm9jYXRpb24YAiABKAsyOy5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0d
  XJlLnJwYy5SZXR1cm5JbnZvY2F0aW9uQhXiPxISEHJldHVybkludm9jYXRpb25IAFIQcmV0dXJuSW52b2NhdGlvbkIHCgV2YWx1Z
  SKdAQoQUHl0aG9uRGF0YUhlYWRlchJUCgN0YWcYASABKAsyNS5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuY29tbW9uLkFjdG9yV
  mlydHVhbElkZW50aXR5QgviPwgSA3RhZ/ABAVIDdGFnEjMKDHBheWxvYWRfdHlwZRgCIAEoCUIQ4j8NEgtwYXlsb2FkVHlwZVILc
  GF5bG9hZFR5cGUi1wEKFFB5dGhvbkNvbnRyb2xNZXNzYWdlElQKA3RhZxgBIAEoCzI1LmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZ
  S5jb21tb24uQWN0b3JWaXJ0dWFsSWRlbnRpdHlCC+I/CBIDdGFn8AEBUgN0YWcSaQoHcGF5bG9hZBgCIAEoCzI+LmVkdS51Y2kua
  WNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUucHl0aG9uLkNvbnRyb2xQYXlsb2FkVjJCD+I/DBIHcGF5bG9hZPABAVIHcGF5b
  G9hZCJuChJQeXRob25BY3Rvck1lc3NhZ2USWAoHcGF5bG9hZBgBIAEoCzItLmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5jb21tb
  24uQWN0b3JDb21tYW5kQg/iPwwSB3BheWxvYWTwAQFSB3BheWxvYWRCC+I/CBABSABYAHgBYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      edu.uci.ics.amber.engine.architecture.rpc.ControlCommandsProto.javaDescriptor,
      edu.uci.ics.amber.engine.architecture.rpc.ControlReturnsProto.javaDescriptor,
      edu.uci.ics.amber.engine.common.VirtualIdentityProto.javaDescriptor,
      edu.uci.ics.amber.engine.common.ActorMessageProto.javaDescriptor,
      scalapb.options.ScalapbProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}