// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.common

object ActorMessageProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    scalapb.options.ScalapbProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      edu.uci.ics.amber.engine.common.Backpressure,
      edu.uci.ics.amber.engine.common.CreditUpdate,
      edu.uci.ics.amber.engine.common.ActorCommandMessage
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CjNlZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvY29tbW9uL2FjdG9yX21lc3NhZ2UucHJvdG8SH2VkdS51Y2kuaWNzLmFtYmVyL
  mVuZ2luZS5jb21tb24aFXNjYWxhcGIvc2NhbGFwYi5wcm90byJYCgxCYWNrcHJlc3N1cmUSSAoTZW5hYmxlX2JhY2twcmVzc3VyZ
  RgBIAEoCEIX4j8UEhJlbmFibGVCYWNrcHJlc3N1cmVSEmVuYWJsZUJhY2twcmVzc3VyZSIOCgxDcmVkaXRVcGRhdGUi7wEKDEFjd
  G9yQ29tbWFuZBJmCgxiYWNrcHJlc3N1cmUYASABKAsyLS5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuY29tbW9uLkJhY2twcmVzc
  3VyZUIR4j8OEgxiYWNrcHJlc3N1cmVIAFIMYmFja3ByZXNzdXJlEmcKDWNyZWRpdF91cGRhdGUYAiABKAsyLS5lZHUudWNpLmljc
  y5hbWJlci5lbmdpbmUuY29tbW9uLkNyZWRpdFVwZGF0ZUIR4j8OEgxjcmVkaXRVcGRhdGVIAFIMY3JlZGl0VXBkYXRlQg4KDHNlY
  WxlZF92YWx1ZUIL4j8IEAFIAFgAeAFiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      scalapb.options.ScalapbProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}