// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.common

@SerialVersionUID(0L)
final case class ExecutionStatsStore(
    startTimestamp: _root_.scala.Long = 0L,
    endTimestamp: _root_.scala.Long = 0L,
    operatorInfo: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, edu.uci.ics.amber.engine.common.OperatorMetrics] = _root_.scala.collection.immutable.Map.empty,
    operatorWorkerMapping: _root_.scala.Seq[edu.uci.ics.amber.engine.common.OperatorWorkerMapping] = _root_.scala.Seq.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ExecutionStatsStore] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = startTimestamp
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(1, __value)
        }
      };
      
      {
        val __value = endTimestamp
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(2, __value)
        }
      };
      operatorInfo.foreach { __item =>
        val __value = edu.uci.ics.amber.engine.common.ExecutionStatsStore._typemapper_operatorInfo.toBase(__item)
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      operatorWorkerMapping.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = startTimestamp
        if (__v != 0L) {
          _output__.writeInt64(1, __v)
        }
      };
      {
        val __v = endTimestamp
        if (__v != 0L) {
          _output__.writeInt64(2, __v)
        }
      };
      operatorInfo.foreach { __v =>
        val __m = edu.uci.ics.amber.engine.common.ExecutionStatsStore._typemapper_operatorInfo.toBase(__v)
        _output__.writeTag(3, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      operatorWorkerMapping.foreach { __v =>
        val __m = __v
        _output__.writeTag(4, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
    }
    def withStartTimestamp(__v: _root_.scala.Long): ExecutionStatsStore = copy(startTimestamp = __v)
    def withEndTimestamp(__v: _root_.scala.Long): ExecutionStatsStore = copy(endTimestamp = __v)
    def clearOperatorInfo = copy(operatorInfo = _root_.scala.collection.immutable.Map.empty)
    def addOperatorInfo(__vs: (_root_.scala.Predef.String, edu.uci.ics.amber.engine.common.OperatorMetrics) *): ExecutionStatsStore = addAllOperatorInfo(__vs)
    def addAllOperatorInfo(__vs: Iterable[(_root_.scala.Predef.String, edu.uci.ics.amber.engine.common.OperatorMetrics)]): ExecutionStatsStore = copy(operatorInfo = operatorInfo ++ __vs)
    def withOperatorInfo(__v: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, edu.uci.ics.amber.engine.common.OperatorMetrics]): ExecutionStatsStore = copy(operatorInfo = __v)
    def clearOperatorWorkerMapping = copy(operatorWorkerMapping = _root_.scala.Seq.empty)
    def addOperatorWorkerMapping(__vs: edu.uci.ics.amber.engine.common.OperatorWorkerMapping *): ExecutionStatsStore = addAllOperatorWorkerMapping(__vs)
    def addAllOperatorWorkerMapping(__vs: Iterable[edu.uci.ics.amber.engine.common.OperatorWorkerMapping]): ExecutionStatsStore = copy(operatorWorkerMapping = operatorWorkerMapping ++ __vs)
    def withOperatorWorkerMapping(__v: _root_.scala.Seq[edu.uci.ics.amber.engine.common.OperatorWorkerMapping]): ExecutionStatsStore = copy(operatorWorkerMapping = __v)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = startTimestamp
          if (__t != 0L) __t else null
        }
        case 2 => {
          val __t = endTimestamp
          if (__t != 0L) __t else null
        }
        case 3 => operatorInfo.iterator.map(edu.uci.ics.amber.engine.common.ExecutionStatsStore._typemapper_operatorInfo.toBase(_)).toSeq
        case 4 => operatorWorkerMapping
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PLong(startTimestamp)
        case 2 => _root_.scalapb.descriptors.PLong(endTimestamp)
        case 3 => _root_.scalapb.descriptors.PRepeated(operatorInfo.iterator.map(edu.uci.ics.amber.engine.common.ExecutionStatsStore._typemapper_operatorInfo.toBase(_).toPMessage).toVector)
        case 4 => _root_.scalapb.descriptors.PRepeated(operatorWorkerMapping.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToSingleLineUnicodeString(this)
    def companion: edu.uci.ics.amber.engine.common.ExecutionStatsStore.type = edu.uci.ics.amber.engine.common.ExecutionStatsStore
    // @@protoc_insertion_point(GeneratedMessage[edu.uci.ics.amber.engine.common.ExecutionStatsStore])
}

object ExecutionStatsStore extends scalapb.GeneratedMessageCompanion[edu.uci.ics.amber.engine.common.ExecutionStatsStore] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[edu.uci.ics.amber.engine.common.ExecutionStatsStore] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): edu.uci.ics.amber.engine.common.ExecutionStatsStore = {
    var __startTimestamp: _root_.scala.Long = 0L
    var __endTimestamp: _root_.scala.Long = 0L
    val __operatorInfo: _root_.scala.collection.mutable.Builder[(_root_.scala.Predef.String, edu.uci.ics.amber.engine.common.OperatorMetrics), _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, edu.uci.ics.amber.engine.common.OperatorMetrics]] = _root_.scala.collection.immutable.Map.newBuilder[_root_.scala.Predef.String, edu.uci.ics.amber.engine.common.OperatorMetrics]
    val __operatorWorkerMapping: _root_.scala.collection.immutable.VectorBuilder[edu.uci.ics.amber.engine.common.OperatorWorkerMapping] = new _root_.scala.collection.immutable.VectorBuilder[edu.uci.ics.amber.engine.common.OperatorWorkerMapping]
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 8 =>
          __startTimestamp = _input__.readInt64()
        case 16 =>
          __endTimestamp = _input__.readInt64()
        case 26 =>
          __operatorInfo += edu.uci.ics.amber.engine.common.ExecutionStatsStore._typemapper_operatorInfo.toCustom(_root_.scalapb.LiteParser.readMessage[edu.uci.ics.amber.engine.common.ExecutionStatsStore.OperatorInfoEntry](_input__))
        case 34 =>
          __operatorWorkerMapping += _root_.scalapb.LiteParser.readMessage[edu.uci.ics.amber.engine.common.OperatorWorkerMapping](_input__)
        case tag => _input__.skipField(tag)
      }
    }
    edu.uci.ics.amber.engine.common.ExecutionStatsStore(
        startTimestamp = __startTimestamp,
        endTimestamp = __endTimestamp,
        operatorInfo = __operatorInfo.result(),
        operatorWorkerMapping = __operatorWorkerMapping.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[edu.uci.ics.amber.engine.common.ExecutionStatsStore] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      edu.uci.ics.amber.engine.common.ExecutionStatsStore(
        startTimestamp = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        endTimestamp = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        operatorInfo = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Seq[edu.uci.ics.amber.engine.common.ExecutionStatsStore.OperatorInfoEntry]]).getOrElse(_root_.scala.Seq.empty).iterator.map(edu.uci.ics.amber.engine.common.ExecutionStatsStore._typemapper_operatorInfo.toCustom(_)).toMap,
        operatorWorkerMapping = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Seq[edu.uci.ics.amber.engine.common.OperatorWorkerMapping]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = WorkflowRuntimeStateProto.javaDescriptor.getMessageTypes().get(7)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = WorkflowRuntimeStateProto.scalaDescriptor.messages(7)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 3 => __out = edu.uci.ics.amber.engine.common.ExecutionStatsStore.OperatorInfoEntry
      case 4 => __out = edu.uci.ics.amber.engine.common.OperatorWorkerMapping
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      _root_.edu.uci.ics.amber.engine.common.ExecutionStatsStore.OperatorInfoEntry
    )
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = edu.uci.ics.amber.engine.common.ExecutionStatsStore(
    startTimestamp = 0L,
    endTimestamp = 0L,
    operatorInfo = _root_.scala.collection.immutable.Map.empty,
    operatorWorkerMapping = _root_.scala.Seq.empty
  )
  @SerialVersionUID(0L)
  final case class OperatorInfoEntry(
      key: _root_.scala.Predef.String = "",
      value: _root_.scala.Option[edu.uci.ics.amber.engine.common.OperatorMetrics] = _root_.scala.None
      ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[OperatorInfoEntry] {
      @transient
      private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
      private[this] def __computeSerializedSize(): _root_.scala.Int = {
        var __size = 0
        
        {
          val __value = key
          if (!__value.isEmpty) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
          }
        };
        if (value.isDefined) {
          val __value = value.get
          __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
        };
        __size
      }
      override def serializedSize: _root_.scala.Int = {
        var __size = __serializedSizeMemoized
        if (__size == 0) {
          __size = __computeSerializedSize() + 1
          __serializedSizeMemoized = __size
        }
        __size - 1
        
      }
      def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
        {
          val __v = key
          if (!__v.isEmpty) {
            _output__.writeString(1, __v)
          }
        };
        value.foreach { __v =>
          val __m = __v
          _output__.writeTag(2, 2)
          _output__.writeUInt32NoTag(__m.serializedSize)
          __m.writeTo(_output__)
        };
      }
      def withKey(__v: _root_.scala.Predef.String): OperatorInfoEntry = copy(key = __v)
      def getValue: edu.uci.ics.amber.engine.common.OperatorMetrics = value.getOrElse(edu.uci.ics.amber.engine.common.OperatorMetrics.defaultInstance)
      def clearValue: OperatorInfoEntry = copy(value = _root_.scala.None)
      def withValue(__v: edu.uci.ics.amber.engine.common.OperatorMetrics): OperatorInfoEntry = copy(value = Option(__v))
      def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
        (__fieldNumber: @_root_.scala.unchecked) match {
          case 1 => {
            val __t = key
            if (__t != "") __t else null
          }
          case 2 => value.orNull
        }
      }
      def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
        _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
        (__field.number: @_root_.scala.unchecked) match {
          case 1 => _root_.scalapb.descriptors.PString(key)
          case 2 => value.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        }
      }
      def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToSingleLineUnicodeString(this)
      def companion: edu.uci.ics.amber.engine.common.ExecutionStatsStore.OperatorInfoEntry.type = edu.uci.ics.amber.engine.common.ExecutionStatsStore.OperatorInfoEntry
      // @@protoc_insertion_point(GeneratedMessage[edu.uci.ics.amber.engine.common.ExecutionStatsStore.OperatorInfoEntry])
  }
  
  object OperatorInfoEntry extends scalapb.GeneratedMessageCompanion[edu.uci.ics.amber.engine.common.ExecutionStatsStore.OperatorInfoEntry] {
    implicit def messageCompanion: scalapb.GeneratedMessageCompanion[edu.uci.ics.amber.engine.common.ExecutionStatsStore.OperatorInfoEntry] = this
    def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): edu.uci.ics.amber.engine.common.ExecutionStatsStore.OperatorInfoEntry = {
      var __key: _root_.scala.Predef.String = ""
      var __value: _root_.scala.Option[edu.uci.ics.amber.engine.common.OperatorMetrics] = _root_.scala.None
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __key = _input__.readStringRequireUtf8()
          case 18 =>
            __value = Option(__value.fold(_root_.scalapb.LiteParser.readMessage[edu.uci.ics.amber.engine.common.OperatorMetrics](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
          case tag => _input__.skipField(tag)
        }
      }
      edu.uci.ics.amber.engine.common.ExecutionStatsStore.OperatorInfoEntry(
          key = __key,
          value = __value
      )
    }
    implicit def messageReads: _root_.scalapb.descriptors.Reads[edu.uci.ics.amber.engine.common.ExecutionStatsStore.OperatorInfoEntry] = _root_.scalapb.descriptors.Reads{
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
        edu.uci.ics.amber.engine.common.ExecutionStatsStore.OperatorInfoEntry(
          key = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
          value = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[edu.uci.ics.amber.engine.common.OperatorMetrics]])
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = edu.uci.ics.amber.engine.common.ExecutionStatsStore.javaDescriptor.getNestedTypes().get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = edu.uci.ics.amber.engine.common.ExecutionStatsStore.scalaDescriptor.nestedMessages(0)
    def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
      var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
      (__number: @_root_.scala.unchecked) match {
        case 2 => __out = edu.uci.ics.amber.engine.common.OperatorMetrics
      }
      __out
    }
    lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
    def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
    lazy val defaultInstance = edu.uci.ics.amber.engine.common.ExecutionStatsStore.OperatorInfoEntry(
      key = "",
      value = _root_.scala.None
    )
    implicit class OperatorInfoEntryLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, edu.uci.ics.amber.engine.common.ExecutionStatsStore.OperatorInfoEntry]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, edu.uci.ics.amber.engine.common.ExecutionStatsStore.OperatorInfoEntry](_l) {
      def key: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.key)((c_, f_) => c_.copy(key = f_))
      def value: _root_.scalapb.lenses.Lens[UpperPB, edu.uci.ics.amber.engine.common.OperatorMetrics] = field(_.getValue)((c_, f_) => c_.copy(value = Option(f_)))
      def optionalValue: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[edu.uci.ics.amber.engine.common.OperatorMetrics]] = field(_.value)((c_, f_) => c_.copy(value = f_))
    }
    final val KEY_FIELD_NUMBER = 1
    final val VALUE_FIELD_NUMBER = 2
    @transient
    implicit val keyValueMapper: _root_.scalapb.TypeMapper[edu.uci.ics.amber.engine.common.ExecutionStatsStore.OperatorInfoEntry, (_root_.scala.Predef.String, edu.uci.ics.amber.engine.common.OperatorMetrics)] =
      _root_.scalapb.TypeMapper[edu.uci.ics.amber.engine.common.ExecutionStatsStore.OperatorInfoEntry, (_root_.scala.Predef.String, edu.uci.ics.amber.engine.common.OperatorMetrics)](__m => (__m.key, __m.getValue))(__p => edu.uci.ics.amber.engine.common.ExecutionStatsStore.OperatorInfoEntry(__p._1, Some(__p._2)))
    def of(
      key: _root_.scala.Predef.String,
      value: _root_.scala.Option[edu.uci.ics.amber.engine.common.OperatorMetrics]
    ): _root_.edu.uci.ics.amber.engine.common.ExecutionStatsStore.OperatorInfoEntry = _root_.edu.uci.ics.amber.engine.common.ExecutionStatsStore.OperatorInfoEntry(
      key,
      value
    )
    // @@protoc_insertion_point(GeneratedMessageCompanion[edu.uci.ics.amber.engine.common.ExecutionStatsStore.OperatorInfoEntry])
  }
  
  implicit class ExecutionStatsStoreLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, edu.uci.ics.amber.engine.common.ExecutionStatsStore]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, edu.uci.ics.amber.engine.common.ExecutionStatsStore](_l) {
    def startTimestamp: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.startTimestamp)((c_, f_) => c_.copy(startTimestamp = f_))
    def endTimestamp: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.endTimestamp)((c_, f_) => c_.copy(endTimestamp = f_))
    def operatorInfo: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, edu.uci.ics.amber.engine.common.OperatorMetrics]] = field(_.operatorInfo)((c_, f_) => c_.copy(operatorInfo = f_))
    def operatorWorkerMapping: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[edu.uci.ics.amber.engine.common.OperatorWorkerMapping]] = field(_.operatorWorkerMapping)((c_, f_) => c_.copy(operatorWorkerMapping = f_))
  }
  final val START_TIMESTAMP_FIELD_NUMBER = 1
  final val END_TIMESTAMP_FIELD_NUMBER = 2
  final val OPERATOR_INFO_FIELD_NUMBER = 3
  final val OPERATOR_WORKER_MAPPING_FIELD_NUMBER = 4
  @transient
  private[common] val _typemapper_operatorInfo: _root_.scalapb.TypeMapper[edu.uci.ics.amber.engine.common.ExecutionStatsStore.OperatorInfoEntry, (_root_.scala.Predef.String, edu.uci.ics.amber.engine.common.OperatorMetrics)] = implicitly[_root_.scalapb.TypeMapper[edu.uci.ics.amber.engine.common.ExecutionStatsStore.OperatorInfoEntry, (_root_.scala.Predef.String, edu.uci.ics.amber.engine.common.OperatorMetrics)]]
  def of(
    startTimestamp: _root_.scala.Long,
    endTimestamp: _root_.scala.Long,
    operatorInfo: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, edu.uci.ics.amber.engine.common.OperatorMetrics],
    operatorWorkerMapping: _root_.scala.Seq[edu.uci.ics.amber.engine.common.OperatorWorkerMapping]
  ): _root_.edu.uci.ics.amber.engine.common.ExecutionStatsStore = _root_.edu.uci.ics.amber.engine.common.ExecutionStatsStore(
    startTimestamp,
    endTimestamp,
    operatorInfo,
    operatorWorkerMapping
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[edu.uci.ics.amber.engine.common.ExecutionStatsStore])
}
