// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.common

object VirtualIdentityProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    scalapb.options.ScalapbProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      edu.uci.ics.amber.engine.common.WorkflowIdentity,
      edu.uci.ics.amber.engine.common.ExecutionIdentity,
      edu.uci.ics.amber.engine.common.ActorVirtualIdentity,
      edu.uci.ics.amber.engine.common.ChannelIdentity,
      edu.uci.ics.amber.engine.common.OperatorIdentity,
      edu.uci.ics.amber.engine.common.PhysicalOpIdentity,
      edu.uci.ics.amber.engine.common.ChannelMarkerIdentity
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CjZlZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvY29tbW9uL3ZpcnR1YWxfaWRlbnRpdHkucHJvdG8SH2VkdS51Y2kuaWNzLmFtY
  mVyLmVuZ2luZS5jb21tb24aFXNjYWxhcGIvc2NhbGFwYi5wcm90byIrChBXb3JrZmxvd0lkZW50aXR5EhcKAmlkGAEgASgDQgfiP
  wQSAmlkUgJpZCIsChFFeGVjdXRpb25JZGVudGl0eRIXCgJpZBgBIAEoA0IH4j8EEgJpZFICaWQiNQoUQWN0b3JWaXJ0dWFsSWRlb
  nRpdHkSHQoEbmFtZRgBIAEoCUIJ4j8GEgRuYW1lUgRuYW1lIqACCg9DaGFubmVsSWRlbnRpdHkScQoOZnJvbV93b3JrZXJfaWQYA
  SABKAsyNS5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuY29tbW9uLkFjdG9yVmlydHVhbElkZW50aXR5QhTiPxESDGZyb21Xb3JrZ
  XJJZPABAVIMZnJvbVdvcmtlcklkEmsKDHRvX3dvcmtlcl9pZBgCIAEoCzI1LmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5jb21tb
  24uQWN0b3JWaXJ0dWFsSWRlbnRpdHlCEuI/DxIKdG9Xb3JrZXJJZPABAVIKdG9Xb3JrZXJJZBItCgppc19jb250cm9sGAMgASgIQ
  g7iPwsSCWlzQ29udHJvbFIJaXNDb250cm9sIisKEE9wZXJhdG9ySWRlbnRpdHkSFwoCaWQYASABKAlCB+I/BBICaWRSAmlkIq8BC
  hJQaHlzaWNhbE9wSWRlbnRpdHkSagoNbG9naWNhbF9vcF9pZBgBIAEoCzIxLmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5jb21tb
  24uT3BlcmF0b3JJZGVudGl0eUIT4j8QEgtsb2dpY2FsT3BJZPABAVILbG9naWNhbE9wSWQSLQoKbGF5ZXJfbmFtZRgCIAEoCUIO4
  j8LEglsYXllck5hbWVSCWxheWVyTmFtZSIwChVDaGFubmVsTWFya2VySWRlbnRpdHkSFwoCaWQYASABKAlCB+I/BBICaWRSAmlkQ
  gviPwgQAUgAWAB4AWIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      scalapb.options.ScalapbProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}