// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.common

object WorkflowProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    edu.uci.ics.amber.engine.common.VirtualIdentityProto,
    scalapb.options.ScalapbProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      edu.uci.ics.amber.engine.common.PortIdentity,
      edu.uci.ics.amber.engine.common.InputPort,
      edu.uci.ics.amber.engine.common.OutputPort,
      edu.uci.ics.amber.engine.common.PhysicalLink
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Ci5lZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvY29tbW9uL3dvcmtmbG93LnByb3RvEh9lZHUudWNpLmljcy5hbWJlci5lbmdpb
  mUuY29tbW9uGjZlZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvY29tbW9uL3ZpcnR1YWxfaWRlbnRpdHkucHJvdG8aFXNjYWxhcGIvc
  2NhbGFwYi5wcm90byJSCgxQb3J0SWRlbnRpdHkSFwoCaWQYASABKAVCB+I/BBICaWRSAmlkEikKCGludGVybmFsGAIgASgIQg3iP
  woSCGludGVybmFsUghpbnRlcm5hbCKzAgoJSW5wdXRQb3J0EkkKAmlkGAEgASgLMi0uZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lL
  mNvbW1vbi5Qb3J0SWRlbnRpdHlCCuI/BxICaWTwAQFSAmlkEjMKDGRpc3BsYXlfbmFtZRgCIAEoCUIQ4j8NEgtkaXNwbGF5TmFtZ
  VILZGlzcGxheU5hbWUSQAoRYWxsb3dfbXVsdGlfbGlua3MYAyABKAhCFOI/ERIPYWxsb3dNdWx0aUxpbmtzUg9hbGxvd011bHRpT
  Glua3MSZAoMZGVwZW5kZW5jaWVzGAQgAygLMi0uZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmNvbW1vbi5Qb3J0SWRlbnRpdHlCE
  eI/DhIMZGVwZW5kZW5jaWVzUgxkZXBlbmRlbmNpZXMitwEKCk91dHB1dFBvcnQSSQoCaWQYASABKAsyLS5lZHUudWNpLmljcy5hb
  WJlci5lbmdpbmUuY29tbW9uLlBvcnRJZGVudGl0eUIK4j8HEgJpZPABAVICaWQSMwoMZGlzcGxheV9uYW1lGAIgASgJQhDiPw0SC
  2Rpc3BsYXlOYW1lUgtkaXNwbGF5TmFtZRIpCghibG9ja2luZxgDIAEoCEIN4j8KEghibG9ja2luZ1IIYmxvY2tpbmcilgMKDFBoe
  XNpY2FsTGluaxJjCgpmcm9tX29wX2lkGAEgASgLMjMuZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmNvbW1vbi5QaHlzaWNhbE9wS
  WRlbnRpdHlCEOI/DRIIZnJvbU9wSWTwAQFSCGZyb21PcElkEmMKDGZyb21fcG9ydF9pZBgCIAEoCzItLmVkdS51Y2kuaWNzLmFtY
  mVyLmVuZ2luZS5jb21tb24uUG9ydElkZW50aXR5QhLiPw8SCmZyb21Qb3J0SWTwAQFSCmZyb21Qb3J0SWQSXQoIdG9fb3BfaWQYA
  yABKAsyMy5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuY29tbW9uLlBoeXNpY2FsT3BJZGVudGl0eUIO4j8LEgZ0b09wSWTwAQFSB
  nRvT3BJZBJdCgp0b19wb3J0X2lkGAQgASgLMi0uZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmNvbW1vbi5Qb3J0SWRlbnRpdHlCE
  OI/DRIIdG9Qb3J0SWTwAQFSCHRvUG9ydElkQgviPwgQAUgAWAB4AGIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      edu.uci.ics.amber.engine.common.VirtualIdentityProto.javaDescriptor,
      scalapb.options.ScalapbProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}