// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.common

object WorkflowMetricsProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    edu.uci.ics.amber.engine.architecture.worker.StatisticsProto,
    edu.uci.ics.amber.engine.common.VirtualIdentityProto,
    scalapb.options.ScalapbProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      edu.uci.ics.amber.engine.common.OperatorStatistics,
      edu.uci.ics.amber.engine.common.OperatorMetrics
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CjZlZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvY29tbW9uL3dvcmtmbG93X21ldHJpY3MucHJvdG8SH2VkdS51Y2kuaWNzLmFtY
  mVyLmVuZ2luZS5jb21tb24aPWVkdS91Y2kvaWNzL2FtYmVyL2VuZ2luZS9hcmNoaXRlY3R1cmUvd29ya2VyL3N0YXRpc3RpY3Muc
  HJvdG8aNmVkdS91Y2kvaWNzL2FtYmVyL2VuZ2luZS9jb21tb24vdmlydHVhbF9pZGVudGl0eS5wcm90bxoVc2NhbGFwYi9zY2FsY
  XBiLnByb3RvIoIEChJPcGVyYXRvclN0YXRpc3RpY3MSdQoLaW5wdXRfY291bnQYASADKAsyQy5lZHUudWNpLmljcy5hbWJlci5lb
  mdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlci5Qb3J0VHVwbGVDb3VudE1hcHBpbmdCD+I/DBIKaW5wdXRDb3VudFIKaW5wdXRDb3Vud
  BJ4CgxvdXRwdXRfY291bnQYAiADKAsyQy5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuYXJjaGl0ZWN0dXJlLndvcmtlci5Qb3J0V
  HVwbGVDb3VudE1hcHBpbmdCEOI/DRILb3V0cHV0Q291bnRSC291dHB1dENvdW50EjAKC251bV93b3JrZXJzGAMgASgFQg/iPwwSC
  m51bVdvcmtlcnNSCm51bVdvcmtlcnMSSQoUZGF0YV9wcm9jZXNzaW5nX3RpbWUYBCABKANCF+I/FBISZGF0YVByb2Nlc3NpbmdUa
  W1lUhJkYXRhUHJvY2Vzc2luZ1RpbWUSUgoXY29udHJvbF9wcm9jZXNzaW5nX3RpbWUYBSABKANCGuI/FxIVY29udHJvbFByb2Nlc
  3NpbmdUaW1lUhVjb250cm9sUHJvY2Vzc2luZ1RpbWUSKgoJaWRsZV90aW1lGAYgASgDQg3iPwoSCGlkbGVUaW1lUghpZGxlVGltZ
  SKMAgoPT3BlcmF0b3JNZXRyaWNzEnYKDm9wZXJhdG9yX3N0YXRlGAEgASgOMjguZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmNvb
  W1vbi5Xb3JrZmxvd0FnZ3JlZ2F0ZWRTdGF0ZUIV4j8SEg1vcGVyYXRvclN0YXRl8AEBUg1vcGVyYXRvclN0YXRlEoABChNvcGVyY
  XRvcl9zdGF0aXN0aWNzGAIgASgLMjMuZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmNvbW1vbi5PcGVyYXRvclN0YXRpc3RpY3NCG
  uI/FxISb3BlcmF0b3JTdGF0aXN0aWNz8AEBUhJvcGVyYXRvclN0YXRpc3RpY3MqrwIKF1dvcmtmbG93QWdncmVnYXRlZFN0YXRlE
  iUKDVVOSU5JVElBTElaRUQQABoS4j8PEg1VTklOSVRJQUxJWkVEEhUKBVJFQURZEAEaCuI/BxIFUkVBRFkSGQoHUlVOTklORxACG
  gziPwkSB1JVTk5JTkcSGQoHUEFVU0lORxADGgziPwkSB1BBVVNJTkcSFwoGUEFVU0VEEAQaC+I/CBIGUEFVU0VEEhsKCFJFU1VNS
  U5HEAUaDeI/ChIIUkVTVU1JTkcSHQoJQ09NUExFVEVEEAYaDuI/CxIJQ09NUExFVEVEEhcKBkZBSUxFRBAHGgviPwgSBkZBSUxFR
  BIZCgdVTktOT1dOEAgaDOI/CRIHVU5LTk9XThIXCgZLSUxMRUQQCRoL4j8IEgZLSUxMRURCC+I/CBABSABYAHgAYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      edu.uci.ics.amber.engine.architecture.worker.StatisticsProto.javaDescriptor,
      edu.uci.ics.amber.engine.common.VirtualIdentityProto.javaDescriptor,
      scalapb.options.ScalapbProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}