// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.architecture.rpc


object WorkerServiceGrpc {
  val METHOD_ADD_INPUT_CHANNEL: _root_.io.grpc.MethodDescriptor[edu.uci.ics.amber.engine.architecture.rpc.AddInputChannelRequest, edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] =
    _root_.io.grpc.MethodDescriptor.newBuilder()
      .setType(_root_.io.grpc.MethodDescriptor.MethodType.UNARY)
      .setFullMethodName(_root_.io.grpc.MethodDescriptor.generateFullMethodName("edu.uci.ics.amber.engine.architecture.rpc.WorkerService", "AddInputChannel"))
      .setSampledToLocalTracing(true)
      .setRequestMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.AddInputChannelRequest])
      .setResponseMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn])
      .setSchemaDescriptor(_root_.scalapb.grpc.ConcreteProtoMethodDescriptorSupplier.fromMethodDescriptor(edu.uci.ics.amber.engine.architecture.rpc.WorkerServiceProto.javaDescriptor.getServices().get(0).getMethods().get(0)))
      .build()
  
  val METHOD_ADD_PARTITIONING: _root_.io.grpc.MethodDescriptor[edu.uci.ics.amber.engine.architecture.rpc.AddPartitioningRequest, edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] =
    _root_.io.grpc.MethodDescriptor.newBuilder()
      .setType(_root_.io.grpc.MethodDescriptor.MethodType.UNARY)
      .setFullMethodName(_root_.io.grpc.MethodDescriptor.generateFullMethodName("edu.uci.ics.amber.engine.architecture.rpc.WorkerService", "AddPartitioning"))
      .setSampledToLocalTracing(true)
      .setRequestMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.AddPartitioningRequest])
      .setResponseMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn])
      .setSchemaDescriptor(_root_.scalapb.grpc.ConcreteProtoMethodDescriptorSupplier.fromMethodDescriptor(edu.uci.ics.amber.engine.architecture.rpc.WorkerServiceProto.javaDescriptor.getServices().get(0).getMethods().get(1)))
      .build()
  
  val METHOD_ASSIGN_PORT: _root_.io.grpc.MethodDescriptor[edu.uci.ics.amber.engine.architecture.rpc.AssignPortRequest, edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] =
    _root_.io.grpc.MethodDescriptor.newBuilder()
      .setType(_root_.io.grpc.MethodDescriptor.MethodType.UNARY)
      .setFullMethodName(_root_.io.grpc.MethodDescriptor.generateFullMethodName("edu.uci.ics.amber.engine.architecture.rpc.WorkerService", "AssignPort"))
      .setSampledToLocalTracing(true)
      .setRequestMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.AssignPortRequest])
      .setResponseMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn])
      .setSchemaDescriptor(_root_.scalapb.grpc.ConcreteProtoMethodDescriptorSupplier.fromMethodDescriptor(edu.uci.ics.amber.engine.architecture.rpc.WorkerServiceProto.javaDescriptor.getServices().get(0).getMethods().get(2)))
      .build()
  
  val METHOD_FINALIZE_CHECKPOINT: _root_.io.grpc.MethodDescriptor[edu.uci.ics.amber.engine.architecture.rpc.FinalizeCheckpointRequest, edu.uci.ics.amber.engine.architecture.rpc.FinalizeCheckpointResponse] =
    _root_.io.grpc.MethodDescriptor.newBuilder()
      .setType(_root_.io.grpc.MethodDescriptor.MethodType.UNARY)
      .setFullMethodName(_root_.io.grpc.MethodDescriptor.generateFullMethodName("edu.uci.ics.amber.engine.architecture.rpc.WorkerService", "FinalizeCheckpoint"))
      .setSampledToLocalTracing(true)
      .setRequestMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.FinalizeCheckpointRequest])
      .setResponseMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.FinalizeCheckpointResponse])
      .setSchemaDescriptor(_root_.scalapb.grpc.ConcreteProtoMethodDescriptorSupplier.fromMethodDescriptor(edu.uci.ics.amber.engine.architecture.rpc.WorkerServiceProto.javaDescriptor.getServices().get(0).getMethods().get(3)))
      .build()
  
  val METHOD_FLUSH_NETWORK_BUFFER: _root_.io.grpc.MethodDescriptor[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] =
    _root_.io.grpc.MethodDescriptor.newBuilder()
      .setType(_root_.io.grpc.MethodDescriptor.MethodType.UNARY)
      .setFullMethodName(_root_.io.grpc.MethodDescriptor.generateFullMethodName("edu.uci.ics.amber.engine.architecture.rpc.WorkerService", "FlushNetworkBuffer"))
      .setSampledToLocalTracing(true)
      .setRequestMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest])
      .setResponseMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn])
      .setSchemaDescriptor(_root_.scalapb.grpc.ConcreteProtoMethodDescriptorSupplier.fromMethodDescriptor(edu.uci.ics.amber.engine.architecture.rpc.WorkerServiceProto.javaDescriptor.getServices().get(0).getMethods().get(4)))
      .build()
  
  val METHOD_INITIALIZE_EXECUTOR: _root_.io.grpc.MethodDescriptor[edu.uci.ics.amber.engine.architecture.rpc.InitializeExecutorRequest, edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] =
    _root_.io.grpc.MethodDescriptor.newBuilder()
      .setType(_root_.io.grpc.MethodDescriptor.MethodType.UNARY)
      .setFullMethodName(_root_.io.grpc.MethodDescriptor.generateFullMethodName("edu.uci.ics.amber.engine.architecture.rpc.WorkerService", "InitializeExecutor"))
      .setSampledToLocalTracing(true)
      .setRequestMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.InitializeExecutorRequest])
      .setResponseMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn])
      .setSchemaDescriptor(_root_.scalapb.grpc.ConcreteProtoMethodDescriptorSupplier.fromMethodDescriptor(edu.uci.ics.amber.engine.architecture.rpc.WorkerServiceProto.javaDescriptor.getServices().get(0).getMethods().get(5)))
      .build()
  
  val METHOD_OPEN_EXECUTOR: _root_.io.grpc.MethodDescriptor[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] =
    _root_.io.grpc.MethodDescriptor.newBuilder()
      .setType(_root_.io.grpc.MethodDescriptor.MethodType.UNARY)
      .setFullMethodName(_root_.io.grpc.MethodDescriptor.generateFullMethodName("edu.uci.ics.amber.engine.architecture.rpc.WorkerService", "OpenExecutor"))
      .setSampledToLocalTracing(true)
      .setRequestMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest])
      .setResponseMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn])
      .setSchemaDescriptor(_root_.scalapb.grpc.ConcreteProtoMethodDescriptorSupplier.fromMethodDescriptor(edu.uci.ics.amber.engine.architecture.rpc.WorkerServiceProto.javaDescriptor.getServices().get(0).getMethods().get(6)))
      .build()
  
  val METHOD_PAUSE_WORKER: _root_.io.grpc.MethodDescriptor[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, edu.uci.ics.amber.engine.architecture.rpc.WorkerStateResponse] =
    _root_.io.grpc.MethodDescriptor.newBuilder()
      .setType(_root_.io.grpc.MethodDescriptor.MethodType.UNARY)
      .setFullMethodName(_root_.io.grpc.MethodDescriptor.generateFullMethodName("edu.uci.ics.amber.engine.architecture.rpc.WorkerService", "PauseWorker"))
      .setSampledToLocalTracing(true)
      .setRequestMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest])
      .setResponseMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.WorkerStateResponse])
      .setSchemaDescriptor(_root_.scalapb.grpc.ConcreteProtoMethodDescriptorSupplier.fromMethodDescriptor(edu.uci.ics.amber.engine.architecture.rpc.WorkerServiceProto.javaDescriptor.getServices().get(0).getMethods().get(7)))
      .build()
  
  val METHOD_PREPARE_CHECKPOINT: _root_.io.grpc.MethodDescriptor[edu.uci.ics.amber.engine.architecture.rpc.PrepareCheckpointRequest, edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] =
    _root_.io.grpc.MethodDescriptor.newBuilder()
      .setType(_root_.io.grpc.MethodDescriptor.MethodType.UNARY)
      .setFullMethodName(_root_.io.grpc.MethodDescriptor.generateFullMethodName("edu.uci.ics.amber.engine.architecture.rpc.WorkerService", "PrepareCheckpoint"))
      .setSampledToLocalTracing(true)
      .setRequestMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.PrepareCheckpointRequest])
      .setResponseMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn])
      .setSchemaDescriptor(_root_.scalapb.grpc.ConcreteProtoMethodDescriptorSupplier.fromMethodDescriptor(edu.uci.ics.amber.engine.architecture.rpc.WorkerServiceProto.javaDescriptor.getServices().get(0).getMethods().get(8)))
      .build()
  
  val METHOD_QUERY_STATISTICS: _root_.io.grpc.MethodDescriptor[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, edu.uci.ics.amber.engine.architecture.rpc.WorkerMetricsResponse] =
    _root_.io.grpc.MethodDescriptor.newBuilder()
      .setType(_root_.io.grpc.MethodDescriptor.MethodType.UNARY)
      .setFullMethodName(_root_.io.grpc.MethodDescriptor.generateFullMethodName("edu.uci.ics.amber.engine.architecture.rpc.WorkerService", "QueryStatistics"))
      .setSampledToLocalTracing(true)
      .setRequestMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest])
      .setResponseMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.WorkerMetricsResponse])
      .setSchemaDescriptor(_root_.scalapb.grpc.ConcreteProtoMethodDescriptorSupplier.fromMethodDescriptor(edu.uci.ics.amber.engine.architecture.rpc.WorkerServiceProto.javaDescriptor.getServices().get(0).getMethods().get(9)))
      .build()
  
  val METHOD_RESUME_WORKER: _root_.io.grpc.MethodDescriptor[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, edu.uci.ics.amber.engine.architecture.rpc.WorkerStateResponse] =
    _root_.io.grpc.MethodDescriptor.newBuilder()
      .setType(_root_.io.grpc.MethodDescriptor.MethodType.UNARY)
      .setFullMethodName(_root_.io.grpc.MethodDescriptor.generateFullMethodName("edu.uci.ics.amber.engine.architecture.rpc.WorkerService", "ResumeWorker"))
      .setSampledToLocalTracing(true)
      .setRequestMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest])
      .setResponseMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.WorkerStateResponse])
      .setSchemaDescriptor(_root_.scalapb.grpc.ConcreteProtoMethodDescriptorSupplier.fromMethodDescriptor(edu.uci.ics.amber.engine.architecture.rpc.WorkerServiceProto.javaDescriptor.getServices().get(0).getMethods().get(10)))
      .build()
  
  val METHOD_RETRIEVE_STATE: _root_.io.grpc.MethodDescriptor[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] =
    _root_.io.grpc.MethodDescriptor.newBuilder()
      .setType(_root_.io.grpc.MethodDescriptor.MethodType.UNARY)
      .setFullMethodName(_root_.io.grpc.MethodDescriptor.generateFullMethodName("edu.uci.ics.amber.engine.architecture.rpc.WorkerService", "RetrieveState"))
      .setSampledToLocalTracing(true)
      .setRequestMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest])
      .setResponseMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn])
      .setSchemaDescriptor(_root_.scalapb.grpc.ConcreteProtoMethodDescriptorSupplier.fromMethodDescriptor(edu.uci.ics.amber.engine.architecture.rpc.WorkerServiceProto.javaDescriptor.getServices().get(0).getMethods().get(11)))
      .build()
  
  val METHOD_RETRY_CURRENT_TUPLE: _root_.io.grpc.MethodDescriptor[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] =
    _root_.io.grpc.MethodDescriptor.newBuilder()
      .setType(_root_.io.grpc.MethodDescriptor.MethodType.UNARY)
      .setFullMethodName(_root_.io.grpc.MethodDescriptor.generateFullMethodName("edu.uci.ics.amber.engine.architecture.rpc.WorkerService", "RetryCurrentTuple"))
      .setSampledToLocalTracing(true)
      .setRequestMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest])
      .setResponseMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn])
      .setSchemaDescriptor(_root_.scalapb.grpc.ConcreteProtoMethodDescriptorSupplier.fromMethodDescriptor(edu.uci.ics.amber.engine.architecture.rpc.WorkerServiceProto.javaDescriptor.getServices().get(0).getMethods().get(12)))
      .build()
  
  val METHOD_START_WORKER: _root_.io.grpc.MethodDescriptor[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, edu.uci.ics.amber.engine.architecture.rpc.WorkerStateResponse] =
    _root_.io.grpc.MethodDescriptor.newBuilder()
      .setType(_root_.io.grpc.MethodDescriptor.MethodType.UNARY)
      .setFullMethodName(_root_.io.grpc.MethodDescriptor.generateFullMethodName("edu.uci.ics.amber.engine.architecture.rpc.WorkerService", "StartWorker"))
      .setSampledToLocalTracing(true)
      .setRequestMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest])
      .setResponseMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.WorkerStateResponse])
      .setSchemaDescriptor(_root_.scalapb.grpc.ConcreteProtoMethodDescriptorSupplier.fromMethodDescriptor(edu.uci.ics.amber.engine.architecture.rpc.WorkerServiceProto.javaDescriptor.getServices().get(0).getMethods().get(13)))
      .build()
  
  val METHOD_DEBUG_COMMAND: _root_.io.grpc.MethodDescriptor[edu.uci.ics.amber.engine.architecture.rpc.DebugCommandRequest, edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] =
    _root_.io.grpc.MethodDescriptor.newBuilder()
      .setType(_root_.io.grpc.MethodDescriptor.MethodType.UNARY)
      .setFullMethodName(_root_.io.grpc.MethodDescriptor.generateFullMethodName("edu.uci.ics.amber.engine.architecture.rpc.WorkerService", "DebugCommand"))
      .setSampledToLocalTracing(true)
      .setRequestMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.DebugCommandRequest])
      .setResponseMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn])
      .setSchemaDescriptor(_root_.scalapb.grpc.ConcreteProtoMethodDescriptorSupplier.fromMethodDescriptor(edu.uci.ics.amber.engine.architecture.rpc.WorkerServiceProto.javaDescriptor.getServices().get(0).getMethods().get(14)))
      .build()
  
  val METHOD_EVALUATE_PYTHON_EXPRESSION: _root_.io.grpc.MethodDescriptor[edu.uci.ics.amber.engine.architecture.rpc.EvaluatePythonExpressionRequest, edu.uci.ics.amber.engine.architecture.rpc.EvaluatedValue] =
    _root_.io.grpc.MethodDescriptor.newBuilder()
      .setType(_root_.io.grpc.MethodDescriptor.MethodType.UNARY)
      .setFullMethodName(_root_.io.grpc.MethodDescriptor.generateFullMethodName("edu.uci.ics.amber.engine.architecture.rpc.WorkerService", "EvaluatePythonExpression"))
      .setSampledToLocalTracing(true)
      .setRequestMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.EvaluatePythonExpressionRequest])
      .setResponseMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.EvaluatedValue])
      .setSchemaDescriptor(_root_.scalapb.grpc.ConcreteProtoMethodDescriptorSupplier.fromMethodDescriptor(edu.uci.ics.amber.engine.architecture.rpc.WorkerServiceProto.javaDescriptor.getServices().get(0).getMethods().get(15)))
      .build()
  
  val METHOD_NO_OPERATION: _root_.io.grpc.MethodDescriptor[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] =
    _root_.io.grpc.MethodDescriptor.newBuilder()
      .setType(_root_.io.grpc.MethodDescriptor.MethodType.UNARY)
      .setFullMethodName(_root_.io.grpc.MethodDescriptor.generateFullMethodName("edu.uci.ics.amber.engine.architecture.rpc.WorkerService", "NoOperation"))
      .setSampledToLocalTracing(true)
      .setRequestMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest])
      .setResponseMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn])
      .setSchemaDescriptor(_root_.scalapb.grpc.ConcreteProtoMethodDescriptorSupplier.fromMethodDescriptor(edu.uci.ics.amber.engine.architecture.rpc.WorkerServiceProto.javaDescriptor.getServices().get(0).getMethods().get(16)))
      .build()
  
  val SERVICE: _root_.io.grpc.ServiceDescriptor =
    _root_.io.grpc.ServiceDescriptor.newBuilder("edu.uci.ics.amber.engine.architecture.rpc.WorkerService")
      .setSchemaDescriptor(new _root_.scalapb.grpc.ConcreteProtoFileDescriptorSupplier(edu.uci.ics.amber.engine.architecture.rpc.WorkerServiceProto.javaDescriptor))
      .addMethod(METHOD_ADD_INPUT_CHANNEL)
      .addMethod(METHOD_ADD_PARTITIONING)
      .addMethod(METHOD_ASSIGN_PORT)
      .addMethod(METHOD_FINALIZE_CHECKPOINT)
      .addMethod(METHOD_FLUSH_NETWORK_BUFFER)
      .addMethod(METHOD_INITIALIZE_EXECUTOR)
      .addMethod(METHOD_OPEN_EXECUTOR)
      .addMethod(METHOD_PAUSE_WORKER)
      .addMethod(METHOD_PREPARE_CHECKPOINT)
      .addMethod(METHOD_QUERY_STATISTICS)
      .addMethod(METHOD_RESUME_WORKER)
      .addMethod(METHOD_RETRIEVE_STATE)
      .addMethod(METHOD_RETRY_CURRENT_TUPLE)
      .addMethod(METHOD_START_WORKER)
      .addMethod(METHOD_DEBUG_COMMAND)
      .addMethod(METHOD_EVALUATE_PYTHON_EXPRESSION)
      .addMethod(METHOD_NO_OPERATION)
      .build()
  
  /** RPC Service
    */
  trait WorkerService extends _root_.scalapb.grpc.AbstractService {
    override def serviceCompanion = WorkerService
    def addInputChannel(request: edu.uci.ics.amber.engine.architecture.rpc.AddInputChannelRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn]
    def addPartitioning(request: edu.uci.ics.amber.engine.architecture.rpc.AddPartitioningRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn]
    def assignPort(request: edu.uci.ics.amber.engine.architecture.rpc.AssignPortRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn]
    def finalizeCheckpoint(request: edu.uci.ics.amber.engine.architecture.rpc.FinalizeCheckpointRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.FinalizeCheckpointResponse]
    def flushNetworkBuffer(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn]
    def initializeExecutor(request: edu.uci.ics.amber.engine.architecture.rpc.InitializeExecutorRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn]
    def openExecutor(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn]
    def pauseWorker(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.WorkerStateResponse]
    def prepareCheckpoint(request: edu.uci.ics.amber.engine.architecture.rpc.PrepareCheckpointRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn]
    def queryStatistics(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.WorkerMetricsResponse]
    def resumeWorker(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.WorkerStateResponse]
    def retrieveState(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn]
    def retryCurrentTuple(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn]
    def startWorker(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.WorkerStateResponse]
    def debugCommand(request: edu.uci.ics.amber.engine.architecture.rpc.DebugCommandRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn]
    def evaluatePythonExpression(request: edu.uci.ics.amber.engine.architecture.rpc.EvaluatePythonExpressionRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.EvaluatedValue]
    def noOperation(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn]
  }
  
  object WorkerService extends _root_.scalapb.grpc.ServiceCompanion[WorkerService] {
    implicit def serviceCompanion: _root_.scalapb.grpc.ServiceCompanion[WorkerService] = this
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.ServiceDescriptor = edu.uci.ics.amber.engine.architecture.rpc.WorkerServiceProto.javaDescriptor.getServices().get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.ServiceDescriptor = edu.uci.ics.amber.engine.architecture.rpc.WorkerServiceProto.scalaDescriptor.services(0)
    def bindService(serviceImpl: WorkerService, executionContext: scala.concurrent.ExecutionContext): _root_.io.grpc.ServerServiceDefinition =
      _root_.io.grpc.ServerServiceDefinition.builder(SERVICE)
      .addMethod(
        METHOD_ADD_INPUT_CHANNEL,
        _root_.io.grpc.stub.ServerCalls.asyncUnaryCall(new _root_.io.grpc.stub.ServerCalls.UnaryMethod[edu.uci.ics.amber.engine.architecture.rpc.AddInputChannelRequest, edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] {
          override def invoke(request: edu.uci.ics.amber.engine.architecture.rpc.AddInputChannelRequest, observer: _root_.io.grpc.stub.StreamObserver[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn]): _root_.scala.Unit =
            serviceImpl.addInputChannel(request).onComplete(scalapb.grpc.Grpc.completeObserver(observer))(
              executionContext)
        }))
      .addMethod(
        METHOD_ADD_PARTITIONING,
        _root_.io.grpc.stub.ServerCalls.asyncUnaryCall(new _root_.io.grpc.stub.ServerCalls.UnaryMethod[edu.uci.ics.amber.engine.architecture.rpc.AddPartitioningRequest, edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] {
          override def invoke(request: edu.uci.ics.amber.engine.architecture.rpc.AddPartitioningRequest, observer: _root_.io.grpc.stub.StreamObserver[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn]): _root_.scala.Unit =
            serviceImpl.addPartitioning(request).onComplete(scalapb.grpc.Grpc.completeObserver(observer))(
              executionContext)
        }))
      .addMethod(
        METHOD_ASSIGN_PORT,
        _root_.io.grpc.stub.ServerCalls.asyncUnaryCall(new _root_.io.grpc.stub.ServerCalls.UnaryMethod[edu.uci.ics.amber.engine.architecture.rpc.AssignPortRequest, edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] {
          override def invoke(request: edu.uci.ics.amber.engine.architecture.rpc.AssignPortRequest, observer: _root_.io.grpc.stub.StreamObserver[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn]): _root_.scala.Unit =
            serviceImpl.assignPort(request).onComplete(scalapb.grpc.Grpc.completeObserver(observer))(
              executionContext)
        }))
      .addMethod(
        METHOD_FINALIZE_CHECKPOINT,
        _root_.io.grpc.stub.ServerCalls.asyncUnaryCall(new _root_.io.grpc.stub.ServerCalls.UnaryMethod[edu.uci.ics.amber.engine.architecture.rpc.FinalizeCheckpointRequest, edu.uci.ics.amber.engine.architecture.rpc.FinalizeCheckpointResponse] {
          override def invoke(request: edu.uci.ics.amber.engine.architecture.rpc.FinalizeCheckpointRequest, observer: _root_.io.grpc.stub.StreamObserver[edu.uci.ics.amber.engine.architecture.rpc.FinalizeCheckpointResponse]): _root_.scala.Unit =
            serviceImpl.finalizeCheckpoint(request).onComplete(scalapb.grpc.Grpc.completeObserver(observer))(
              executionContext)
        }))
      .addMethod(
        METHOD_FLUSH_NETWORK_BUFFER,
        _root_.io.grpc.stub.ServerCalls.asyncUnaryCall(new _root_.io.grpc.stub.ServerCalls.UnaryMethod[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] {
          override def invoke(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, observer: _root_.io.grpc.stub.StreamObserver[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn]): _root_.scala.Unit =
            serviceImpl.flushNetworkBuffer(request).onComplete(scalapb.grpc.Grpc.completeObserver(observer))(
              executionContext)
        }))
      .addMethod(
        METHOD_INITIALIZE_EXECUTOR,
        _root_.io.grpc.stub.ServerCalls.asyncUnaryCall(new _root_.io.grpc.stub.ServerCalls.UnaryMethod[edu.uci.ics.amber.engine.architecture.rpc.InitializeExecutorRequest, edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] {
          override def invoke(request: edu.uci.ics.amber.engine.architecture.rpc.InitializeExecutorRequest, observer: _root_.io.grpc.stub.StreamObserver[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn]): _root_.scala.Unit =
            serviceImpl.initializeExecutor(request).onComplete(scalapb.grpc.Grpc.completeObserver(observer))(
              executionContext)
        }))
      .addMethod(
        METHOD_OPEN_EXECUTOR,
        _root_.io.grpc.stub.ServerCalls.asyncUnaryCall(new _root_.io.grpc.stub.ServerCalls.UnaryMethod[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] {
          override def invoke(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, observer: _root_.io.grpc.stub.StreamObserver[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn]): _root_.scala.Unit =
            serviceImpl.openExecutor(request).onComplete(scalapb.grpc.Grpc.completeObserver(observer))(
              executionContext)
        }))
      .addMethod(
        METHOD_PAUSE_WORKER,
        _root_.io.grpc.stub.ServerCalls.asyncUnaryCall(new _root_.io.grpc.stub.ServerCalls.UnaryMethod[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, edu.uci.ics.amber.engine.architecture.rpc.WorkerStateResponse] {
          override def invoke(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, observer: _root_.io.grpc.stub.StreamObserver[edu.uci.ics.amber.engine.architecture.rpc.WorkerStateResponse]): _root_.scala.Unit =
            serviceImpl.pauseWorker(request).onComplete(scalapb.grpc.Grpc.completeObserver(observer))(
              executionContext)
        }))
      .addMethod(
        METHOD_PREPARE_CHECKPOINT,
        _root_.io.grpc.stub.ServerCalls.asyncUnaryCall(new _root_.io.grpc.stub.ServerCalls.UnaryMethod[edu.uci.ics.amber.engine.architecture.rpc.PrepareCheckpointRequest, edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] {
          override def invoke(request: edu.uci.ics.amber.engine.architecture.rpc.PrepareCheckpointRequest, observer: _root_.io.grpc.stub.StreamObserver[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn]): _root_.scala.Unit =
            serviceImpl.prepareCheckpoint(request).onComplete(scalapb.grpc.Grpc.completeObserver(observer))(
              executionContext)
        }))
      .addMethod(
        METHOD_QUERY_STATISTICS,
        _root_.io.grpc.stub.ServerCalls.asyncUnaryCall(new _root_.io.grpc.stub.ServerCalls.UnaryMethod[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, edu.uci.ics.amber.engine.architecture.rpc.WorkerMetricsResponse] {
          override def invoke(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, observer: _root_.io.grpc.stub.StreamObserver[edu.uci.ics.amber.engine.architecture.rpc.WorkerMetricsResponse]): _root_.scala.Unit =
            serviceImpl.queryStatistics(request).onComplete(scalapb.grpc.Grpc.completeObserver(observer))(
              executionContext)
        }))
      .addMethod(
        METHOD_RESUME_WORKER,
        _root_.io.grpc.stub.ServerCalls.asyncUnaryCall(new _root_.io.grpc.stub.ServerCalls.UnaryMethod[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, edu.uci.ics.amber.engine.architecture.rpc.WorkerStateResponse] {
          override def invoke(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, observer: _root_.io.grpc.stub.StreamObserver[edu.uci.ics.amber.engine.architecture.rpc.WorkerStateResponse]): _root_.scala.Unit =
            serviceImpl.resumeWorker(request).onComplete(scalapb.grpc.Grpc.completeObserver(observer))(
              executionContext)
        }))
      .addMethod(
        METHOD_RETRIEVE_STATE,
        _root_.io.grpc.stub.ServerCalls.asyncUnaryCall(new _root_.io.grpc.stub.ServerCalls.UnaryMethod[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] {
          override def invoke(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, observer: _root_.io.grpc.stub.StreamObserver[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn]): _root_.scala.Unit =
            serviceImpl.retrieveState(request).onComplete(scalapb.grpc.Grpc.completeObserver(observer))(
              executionContext)
        }))
      .addMethod(
        METHOD_RETRY_CURRENT_TUPLE,
        _root_.io.grpc.stub.ServerCalls.asyncUnaryCall(new _root_.io.grpc.stub.ServerCalls.UnaryMethod[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] {
          override def invoke(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, observer: _root_.io.grpc.stub.StreamObserver[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn]): _root_.scala.Unit =
            serviceImpl.retryCurrentTuple(request).onComplete(scalapb.grpc.Grpc.completeObserver(observer))(
              executionContext)
        }))
      .addMethod(
        METHOD_START_WORKER,
        _root_.io.grpc.stub.ServerCalls.asyncUnaryCall(new _root_.io.grpc.stub.ServerCalls.UnaryMethod[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, edu.uci.ics.amber.engine.architecture.rpc.WorkerStateResponse] {
          override def invoke(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, observer: _root_.io.grpc.stub.StreamObserver[edu.uci.ics.amber.engine.architecture.rpc.WorkerStateResponse]): _root_.scala.Unit =
            serviceImpl.startWorker(request).onComplete(scalapb.grpc.Grpc.completeObserver(observer))(
              executionContext)
        }))
      .addMethod(
        METHOD_DEBUG_COMMAND,
        _root_.io.grpc.stub.ServerCalls.asyncUnaryCall(new _root_.io.grpc.stub.ServerCalls.UnaryMethod[edu.uci.ics.amber.engine.architecture.rpc.DebugCommandRequest, edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] {
          override def invoke(request: edu.uci.ics.amber.engine.architecture.rpc.DebugCommandRequest, observer: _root_.io.grpc.stub.StreamObserver[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn]): _root_.scala.Unit =
            serviceImpl.debugCommand(request).onComplete(scalapb.grpc.Grpc.completeObserver(observer))(
              executionContext)
        }))
      .addMethod(
        METHOD_EVALUATE_PYTHON_EXPRESSION,
        _root_.io.grpc.stub.ServerCalls.asyncUnaryCall(new _root_.io.grpc.stub.ServerCalls.UnaryMethod[edu.uci.ics.amber.engine.architecture.rpc.EvaluatePythonExpressionRequest, edu.uci.ics.amber.engine.architecture.rpc.EvaluatedValue] {
          override def invoke(request: edu.uci.ics.amber.engine.architecture.rpc.EvaluatePythonExpressionRequest, observer: _root_.io.grpc.stub.StreamObserver[edu.uci.ics.amber.engine.architecture.rpc.EvaluatedValue]): _root_.scala.Unit =
            serviceImpl.evaluatePythonExpression(request).onComplete(scalapb.grpc.Grpc.completeObserver(observer))(
              executionContext)
        }))
      .addMethod(
        METHOD_NO_OPERATION,
        _root_.io.grpc.stub.ServerCalls.asyncUnaryCall(new _root_.io.grpc.stub.ServerCalls.UnaryMethod[edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] {
          override def invoke(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest, observer: _root_.io.grpc.stub.StreamObserver[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn]): _root_.scala.Unit =
            serviceImpl.noOperation(request).onComplete(scalapb.grpc.Grpc.completeObserver(observer))(
              executionContext)
        }))
      .build()
  }
  
  /** RPC Service
    */
  trait WorkerServiceBlockingClient {
    def serviceCompanion = WorkerService
    def addInputChannel(request: edu.uci.ics.amber.engine.architecture.rpc.AddInputChannelRequest): edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn
    def addPartitioning(request: edu.uci.ics.amber.engine.architecture.rpc.AddPartitioningRequest): edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn
    def assignPort(request: edu.uci.ics.amber.engine.architecture.rpc.AssignPortRequest): edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn
    def finalizeCheckpoint(request: edu.uci.ics.amber.engine.architecture.rpc.FinalizeCheckpointRequest): edu.uci.ics.amber.engine.architecture.rpc.FinalizeCheckpointResponse
    def flushNetworkBuffer(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn
    def initializeExecutor(request: edu.uci.ics.amber.engine.architecture.rpc.InitializeExecutorRequest): edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn
    def openExecutor(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn
    def pauseWorker(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): edu.uci.ics.amber.engine.architecture.rpc.WorkerStateResponse
    def prepareCheckpoint(request: edu.uci.ics.amber.engine.architecture.rpc.PrepareCheckpointRequest): edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn
    def queryStatistics(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): edu.uci.ics.amber.engine.architecture.rpc.WorkerMetricsResponse
    def resumeWorker(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): edu.uci.ics.amber.engine.architecture.rpc.WorkerStateResponse
    def retrieveState(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn
    def retryCurrentTuple(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn
    def startWorker(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): edu.uci.ics.amber.engine.architecture.rpc.WorkerStateResponse
    def debugCommand(request: edu.uci.ics.amber.engine.architecture.rpc.DebugCommandRequest): edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn
    def evaluatePythonExpression(request: edu.uci.ics.amber.engine.architecture.rpc.EvaluatePythonExpressionRequest): edu.uci.ics.amber.engine.architecture.rpc.EvaluatedValue
    def noOperation(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn
  }
  
  class WorkerServiceBlockingStub(channel: _root_.io.grpc.Channel, options: _root_.io.grpc.CallOptions = _root_.io.grpc.CallOptions.DEFAULT) extends _root_.io.grpc.stub.AbstractStub[WorkerServiceBlockingStub](channel, options) with WorkerServiceBlockingClient {
    override def addInputChannel(request: edu.uci.ics.amber.engine.architecture.rpc.AddInputChannelRequest): edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn = {
      _root_.scalapb.grpc.ClientCalls.blockingUnaryCall(channel, METHOD_ADD_INPUT_CHANNEL, options, request)
    }
    
    override def addPartitioning(request: edu.uci.ics.amber.engine.architecture.rpc.AddPartitioningRequest): edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn = {
      _root_.scalapb.grpc.ClientCalls.blockingUnaryCall(channel, METHOD_ADD_PARTITIONING, options, request)
    }
    
    override def assignPort(request: edu.uci.ics.amber.engine.architecture.rpc.AssignPortRequest): edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn = {
      _root_.scalapb.grpc.ClientCalls.blockingUnaryCall(channel, METHOD_ASSIGN_PORT, options, request)
    }
    
    override def finalizeCheckpoint(request: edu.uci.ics.amber.engine.architecture.rpc.FinalizeCheckpointRequest): edu.uci.ics.amber.engine.architecture.rpc.FinalizeCheckpointResponse = {
      _root_.scalapb.grpc.ClientCalls.blockingUnaryCall(channel, METHOD_FINALIZE_CHECKPOINT, options, request)
    }
    
    override def flushNetworkBuffer(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn = {
      _root_.scalapb.grpc.ClientCalls.blockingUnaryCall(channel, METHOD_FLUSH_NETWORK_BUFFER, options, request)
    }
    
    override def initializeExecutor(request: edu.uci.ics.amber.engine.architecture.rpc.InitializeExecutorRequest): edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn = {
      _root_.scalapb.grpc.ClientCalls.blockingUnaryCall(channel, METHOD_INITIALIZE_EXECUTOR, options, request)
    }
    
    override def openExecutor(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn = {
      _root_.scalapb.grpc.ClientCalls.blockingUnaryCall(channel, METHOD_OPEN_EXECUTOR, options, request)
    }
    
    override def pauseWorker(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): edu.uci.ics.amber.engine.architecture.rpc.WorkerStateResponse = {
      _root_.scalapb.grpc.ClientCalls.blockingUnaryCall(channel, METHOD_PAUSE_WORKER, options, request)
    }
    
    override def prepareCheckpoint(request: edu.uci.ics.amber.engine.architecture.rpc.PrepareCheckpointRequest): edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn = {
      _root_.scalapb.grpc.ClientCalls.blockingUnaryCall(channel, METHOD_PREPARE_CHECKPOINT, options, request)
    }
    
    override def queryStatistics(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): edu.uci.ics.amber.engine.architecture.rpc.WorkerMetricsResponse = {
      _root_.scalapb.grpc.ClientCalls.blockingUnaryCall(channel, METHOD_QUERY_STATISTICS, options, request)
    }
    
    override def resumeWorker(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): edu.uci.ics.amber.engine.architecture.rpc.WorkerStateResponse = {
      _root_.scalapb.grpc.ClientCalls.blockingUnaryCall(channel, METHOD_RESUME_WORKER, options, request)
    }
    
    override def retrieveState(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn = {
      _root_.scalapb.grpc.ClientCalls.blockingUnaryCall(channel, METHOD_RETRIEVE_STATE, options, request)
    }
    
    override def retryCurrentTuple(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn = {
      _root_.scalapb.grpc.ClientCalls.blockingUnaryCall(channel, METHOD_RETRY_CURRENT_TUPLE, options, request)
    }
    
    override def startWorker(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): edu.uci.ics.amber.engine.architecture.rpc.WorkerStateResponse = {
      _root_.scalapb.grpc.ClientCalls.blockingUnaryCall(channel, METHOD_START_WORKER, options, request)
    }
    
    override def debugCommand(request: edu.uci.ics.amber.engine.architecture.rpc.DebugCommandRequest): edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn = {
      _root_.scalapb.grpc.ClientCalls.blockingUnaryCall(channel, METHOD_DEBUG_COMMAND, options, request)
    }
    
    override def evaluatePythonExpression(request: edu.uci.ics.amber.engine.architecture.rpc.EvaluatePythonExpressionRequest): edu.uci.ics.amber.engine.architecture.rpc.EvaluatedValue = {
      _root_.scalapb.grpc.ClientCalls.blockingUnaryCall(channel, METHOD_EVALUATE_PYTHON_EXPRESSION, options, request)
    }
    
    override def noOperation(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn = {
      _root_.scalapb.grpc.ClientCalls.blockingUnaryCall(channel, METHOD_NO_OPERATION, options, request)
    }
    
    override def build(channel: _root_.io.grpc.Channel, options: _root_.io.grpc.CallOptions): WorkerServiceBlockingStub = new WorkerServiceBlockingStub(channel, options)
  }
  
  class WorkerServiceStub(channel: _root_.io.grpc.Channel, options: _root_.io.grpc.CallOptions = _root_.io.grpc.CallOptions.DEFAULT) extends _root_.io.grpc.stub.AbstractStub[WorkerServiceStub](channel, options) with WorkerService {
    override def addInputChannel(request: edu.uci.ics.amber.engine.architecture.rpc.AddInputChannelRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] = {
      _root_.scalapb.grpc.ClientCalls.asyncUnaryCall(channel, METHOD_ADD_INPUT_CHANNEL, options, request)
    }
    
    override def addPartitioning(request: edu.uci.ics.amber.engine.architecture.rpc.AddPartitioningRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] = {
      _root_.scalapb.grpc.ClientCalls.asyncUnaryCall(channel, METHOD_ADD_PARTITIONING, options, request)
    }
    
    override def assignPort(request: edu.uci.ics.amber.engine.architecture.rpc.AssignPortRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] = {
      _root_.scalapb.grpc.ClientCalls.asyncUnaryCall(channel, METHOD_ASSIGN_PORT, options, request)
    }
    
    override def finalizeCheckpoint(request: edu.uci.ics.amber.engine.architecture.rpc.FinalizeCheckpointRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.FinalizeCheckpointResponse] = {
      _root_.scalapb.grpc.ClientCalls.asyncUnaryCall(channel, METHOD_FINALIZE_CHECKPOINT, options, request)
    }
    
    override def flushNetworkBuffer(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] = {
      _root_.scalapb.grpc.ClientCalls.asyncUnaryCall(channel, METHOD_FLUSH_NETWORK_BUFFER, options, request)
    }
    
    override def initializeExecutor(request: edu.uci.ics.amber.engine.architecture.rpc.InitializeExecutorRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] = {
      _root_.scalapb.grpc.ClientCalls.asyncUnaryCall(channel, METHOD_INITIALIZE_EXECUTOR, options, request)
    }
    
    override def openExecutor(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] = {
      _root_.scalapb.grpc.ClientCalls.asyncUnaryCall(channel, METHOD_OPEN_EXECUTOR, options, request)
    }
    
    override def pauseWorker(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.WorkerStateResponse] = {
      _root_.scalapb.grpc.ClientCalls.asyncUnaryCall(channel, METHOD_PAUSE_WORKER, options, request)
    }
    
    override def prepareCheckpoint(request: edu.uci.ics.amber.engine.architecture.rpc.PrepareCheckpointRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] = {
      _root_.scalapb.grpc.ClientCalls.asyncUnaryCall(channel, METHOD_PREPARE_CHECKPOINT, options, request)
    }
    
    override def queryStatistics(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.WorkerMetricsResponse] = {
      _root_.scalapb.grpc.ClientCalls.asyncUnaryCall(channel, METHOD_QUERY_STATISTICS, options, request)
    }
    
    override def resumeWorker(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.WorkerStateResponse] = {
      _root_.scalapb.grpc.ClientCalls.asyncUnaryCall(channel, METHOD_RESUME_WORKER, options, request)
    }
    
    override def retrieveState(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] = {
      _root_.scalapb.grpc.ClientCalls.asyncUnaryCall(channel, METHOD_RETRIEVE_STATE, options, request)
    }
    
    override def retryCurrentTuple(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] = {
      _root_.scalapb.grpc.ClientCalls.asyncUnaryCall(channel, METHOD_RETRY_CURRENT_TUPLE, options, request)
    }
    
    override def startWorker(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.WorkerStateResponse] = {
      _root_.scalapb.grpc.ClientCalls.asyncUnaryCall(channel, METHOD_START_WORKER, options, request)
    }
    
    override def debugCommand(request: edu.uci.ics.amber.engine.architecture.rpc.DebugCommandRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] = {
      _root_.scalapb.grpc.ClientCalls.asyncUnaryCall(channel, METHOD_DEBUG_COMMAND, options, request)
    }
    
    override def evaluatePythonExpression(request: edu.uci.ics.amber.engine.architecture.rpc.EvaluatePythonExpressionRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.EvaluatedValue] = {
      _root_.scalapb.grpc.ClientCalls.asyncUnaryCall(channel, METHOD_EVALUATE_PYTHON_EXPRESSION, options, request)
    }
    
    override def noOperation(request: edu.uci.ics.amber.engine.architecture.rpc.EmptyRequest): scala.concurrent.Future[edu.uci.ics.amber.engine.architecture.rpc.EmptyReturn] = {
      _root_.scalapb.grpc.ClientCalls.asyncUnaryCall(channel, METHOD_NO_OPERATION, options, request)
    }
    
    override def build(channel: _root_.io.grpc.Channel, options: _root_.io.grpc.CallOptions): WorkerServiceStub = new WorkerServiceStub(channel, options)
  }
  
  object WorkerServiceStub extends _root_.io.grpc.stub.AbstractStub.StubFactory[WorkerServiceStub] {
    override def newStub(channel: _root_.io.grpc.Channel, options: _root_.io.grpc.CallOptions): WorkerServiceStub = new WorkerServiceStub(channel, options)
    
    implicit val stubFactory: _root_.io.grpc.stub.AbstractStub.StubFactory[WorkerServiceStub] = this
  }
  
  def bindService(serviceImpl: WorkerService, executionContext: scala.concurrent.ExecutionContext): _root_.io.grpc.ServerServiceDefinition = WorkerService.bindService(serviceImpl, executionContext)
  
  def blockingStub(channel: _root_.io.grpc.Channel): WorkerServiceBlockingStub = new WorkerServiceBlockingStub(channel)
  
  def stub(channel: _root_.io.grpc.Channel): WorkerServiceStub = new WorkerServiceStub(channel)
  
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.ServiceDescriptor = edu.uci.ics.amber.engine.architecture.rpc.WorkerServiceProto.javaDescriptor.getServices().get(0)
  
}