// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package edu.uci.ics.amber.engine.architecture.sendsemantics

object PartitioningsProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    scalapb.options.ScalapbProto,
    edu.uci.ics.amber.engine.common.VirtualIdentityProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      edu.uci.ics.amber.engine.architecture.sendsemantics.PartitioningMessage,
      edu.uci.ics.amber.engine.architecture.sendsemantics.OneToOnePartitioning,
      edu.uci.ics.amber.engine.architecture.sendsemantics.RoundRobinPartitioning,
      edu.uci.ics.amber.engine.architecture.sendsemantics.HashBasedShufflePartitioning,
      edu.uci.ics.amber.engine.architecture.sendsemantics.RangeBasedShufflePartitioning,
      edu.uci.ics.amber.engine.architecture.sendsemantics.BroadcastPartitioning
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CkdlZHUvdWNpL2ljcy9hbWJlci9lbmdpbmUvYXJjaGl0ZWN0dXJlL3NlbmRzZW1hbnRpY3MvcGFydGl0aW9uaW5ncy5wcm90b
  xIzZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS5zZW5kc2VtYW50aWNzGhVzY2FsYXBiL3NjYWxhcGIucHJvd
  G8aNmVkdS91Y2kvaWNzL2FtYmVyL2VuZ2luZS9jb21tb24vdmlydHVhbF9pZGVudGl0eS5wcm90byKLBwoMUGFydGl0aW9uaW5nE
  p0BChdvbmVfdG9fb25lX3BhcnRpdGlvbmluZxgBIAEoCzJJLmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUuc
  2VuZHNlbWFudGljcy5PbmVUb09uZVBhcnRpdGlvbmluZ0IZ4j8WEhRvbmVUb09uZVBhcnRpdGlvbmluZ0gAUhRvbmVUb09uZVBhc
  nRpdGlvbmluZxKkAQoYcm91bmRfcm9iaW5fcGFydGl0aW9uaW5nGAIgASgLMksuZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY
  2hpdGVjdHVyZS5zZW5kc2VtYW50aWNzLlJvdW5kUm9iaW5QYXJ0aXRpb25pbmdCG+I/GBIWcm91bmRSb2JpblBhcnRpdGlvbmluZ
  0gAUhZyb3VuZFJvYmluUGFydGl0aW9uaW5nEr0BCh9oYXNoX2Jhc2VkX3NodWZmbGVfcGFydGl0aW9uaW5nGAMgASgLMlEuZWR1L
  nVjaS5pY3MuYW1iZXIuZW5naW5lLmFyY2hpdGVjdHVyZS5zZW5kc2VtYW50aWNzLkhhc2hCYXNlZFNodWZmbGVQYXJ0aXRpb25pb
  mdCIeI/HhIcaGFzaEJhc2VkU2h1ZmZsZVBhcnRpdGlvbmluZ0gAUhxoYXNoQmFzZWRTaHVmZmxlUGFydGl0aW9uaW5nEsEBCiByY
  W5nZV9iYXNlZF9zaHVmZmxlX3BhcnRpdGlvbmluZxgEIAEoCzJSLmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1c
  mUuc2VuZHNlbWFudGljcy5SYW5nZUJhc2VkU2h1ZmZsZVBhcnRpdGlvbmluZ0Ii4j8fEh1yYW5nZUJhc2VkU2h1ZmZsZVBhcnRpd
  GlvbmluZ0gAUh1yYW5nZUJhc2VkU2h1ZmZsZVBhcnRpdGlvbmluZxKfAQoWYnJvYWRjYXN0X3BhcnRpdGlvbmluZxgFIAEoCzJKL
  mVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5hcmNoaXRlY3R1cmUuc2VuZHNlbWFudGljcy5Ccm9hZGNhc3RQYXJ0aXRpb25pbmdCG
  uI/FxIVYnJvYWRjYXN0UGFydGl0aW9uaW5nSABSFWJyb2FkY2FzdFBhcnRpdGlvbmluZ0IOCgxzZWFsZWRfdmFsdWUiogEKFE9uZ
  VRvT25lUGFydGl0aW9uaW5nEi0KCmJhdGNoX3NpemUYASABKAVCDuI/CxIJYmF0Y2hTaXplUgliYXRjaFNpemUSWwoIY2hhbm5lb
  HMYAiADKAsyMC5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuY29tbW9uLkNoYW5uZWxJZGVudGl0eUIN4j8KEghjaGFubmVsc1IIY
  2hhbm5lbHMipAEKFlJvdW5kUm9iaW5QYXJ0aXRpb25pbmcSLQoKYmF0Y2hfc2l6ZRgBIAEoBUIO4j8LEgliYXRjaFNpemVSCWJhd
  GNoU2l6ZRJbCghjaGFubmVscxgCIAMoCzIwLmVkdS51Y2kuaWNzLmFtYmVyLmVuZ2luZS5jb21tb24uQ2hhbm5lbElkZW50aXR5Q
  g3iPwoSCGNoYW5uZWxzUghjaGFubmVscyL1AQocSGFzaEJhc2VkU2h1ZmZsZVBhcnRpdGlvbmluZxItCgpiYXRjaF9zaXplGAEgA
  SgFQg7iPwsSCWJhdGNoU2l6ZVIJYmF0Y2hTaXplElsKCGNoYW5uZWxzGAIgAygLMjAuZWR1LnVjaS5pY3MuYW1iZXIuZW5naW5lL
  mNvbW1vbi5DaGFubmVsSWRlbnRpdHlCDeI/ChIIY2hhbm5lbHNSCGNoYW5uZWxzEkkKFGhhc2hfYXR0cmlidXRlX25hbWVzGAMgA
  ygJQhfiPxQSEmhhc2hBdHRyaWJ1dGVOYW1lc1ISaGFzaEF0dHJpYnV0ZU5hbWVzItECCh1SYW5nZUJhc2VkU2h1ZmZsZVBhcnRpd
  GlvbmluZxItCgpiYXRjaF9zaXplGAEgASgFQg7iPwsSCWJhdGNoU2l6ZVIJYmF0Y2hTaXplElsKCGNoYW5uZWxzGAIgAygLMjAuZ
  WR1LnVjaS5pY3MuYW1iZXIuZW5naW5lLmNvbW1vbi5DaGFubmVsSWRlbnRpdHlCDeI/ChIIY2hhbm5lbHNSCGNoYW5uZWxzEkwKF
  XJhbmdlX2F0dHJpYnV0ZV9uYW1lcxgDIAMoCUIY4j8VEhNyYW5nZUF0dHJpYnV0ZU5hbWVzUhNyYW5nZUF0dHJpYnV0ZU5hbWVzE
  ioKCXJhbmdlX21pbhgEIAEoA0IN4j8KEghyYW5nZU1pblIIcmFuZ2VNaW4SKgoJcmFuZ2VfbWF4GAUgASgDQg3iPwoSCHJhbmdlT
  WF4UghyYW5nZU1heCKjAQoVQnJvYWRjYXN0UGFydGl0aW9uaW5nEi0KCmJhdGNoX3NpemUYASABKAVCDuI/CxIJYmF0Y2hTaXplU
  gliYXRjaFNpemUSWwoIY2hhbm5lbHMYAiADKAsyMC5lZHUudWNpLmljcy5hbWJlci5lbmdpbmUuY29tbW9uLkNoYW5uZWxJZGVud
  Gl0eUIN4j8KEghjaGFubmVsc1IIY2hhbm5lbHNCC+I/CBABSABYAHgBYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      scalapb.options.ScalapbProto.javaDescriptor,
      edu.uci.ics.amber.engine.common.VirtualIdentityProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}