name: Pull Request Stats

on:
  push:
    branches:
      - 'xinyuan-stats'
jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          period: 700
          charts: "REVIEWS"
  
